"""
codegen_dem.py
ON-DEM WG3 - DEM Exporter Code Generator

Reads the ON-DEM schema (parsed by schema_parser.py) and a DEM field
mapping (e.g., yade_mapping.json) and emits a complete export_dem_vtkhdf.py.

Usage:
    python codegen_dem.py <schema_dir> [--mapping dem_mapping.json] [--out export_dem_vtkhdf.py]

Example:
    python codegen_dem.py ./schema --mapping yade_mapping.json --out export_yade_vtkhdf.py
"""

import json
import os
import sys
import argparse
from textwrap import indent, dedent
from datetime import date

from schema_parser import parse_schema_dir, Schema, ClassDef, FieldDef


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_mapping(mapping_path: str) -> dict:
    with open(mapping_path, encoding="utf-8") as f:
        return json.load(f)


def _lookup_mapping(mapping: dict, class_name: str, field_name: str):
    """Look up the YADE expression for a schema field.
    Precedence: class.field > field fallback.
    Returns None if not found.
    """
    cls_entry = mapping.get(class_name, {})
    if field_name in cls_entry:
        return cls_entry[field_name]
    # Search all class entries for the field (less specific fallback)
    for k, v in mapping.items():
        if k.startswith("_"):
            continue
        if isinstance(v, dict) and field_name in v:
            return v[field_name]
    return None


def _hdf5_write_expr(field: FieldDef, yade_expr: str, group_var: str,
                     scalar_as_dataset: bool = False) -> str:
    """Return a code line to write one field using hdf5_utils.hdf5_write_field."""
    n = field.name
    h = field.hdf5_type
    return f'hdf5_write_field({group_var}, "{n}", "{h}", {yade_expr}, scalar_as_dataset={scalar_as_dataset})'


# ---------------------------------------------------------------------------
# Section generators
# ---------------------------------------------------------------------------

def _gen_header(schema_dir: str, mapping_path: str) -> str:
    return f'''\
"""
export_yade_vtkhdf.py
ON-DEM WG3 - YADE to VTKHDF exporter

AUTO-GENERATED by codegen_yade.py on {date.today().isoformat()}
  Schema dir : {schema_dir}
  Mapping    : {mapping_path}

DO NOT EDIT MANUALLY - re-run the generator to update.

Usage (inside YADE or from yadedaily -x):
    from export_yade_vtkhdf import export_vtkhdf
    export_vtkhdf("output.vtkhdf")      # default groups: spheres -> 'Points', other shapes -> 'Others'

    # user-defined display groups (names are required when display_group is given)
    export_vtkhdf("output.vtkhdf",
                  display_group_names=["particles", "geometry"],
                  display_group=lambda b: 0 if isinstance(b.shape, Sphere) else 1)

Periodic engine usage (one timestep per file):
    O.engines += [PyRunner(
        command='export_vtkhdf("sim_%04d.vtkhdf" % O.iter)',
        iterPeriod=1000)]
"""

import numpy as np
import h5py
import os
import sys

from hdf5_utils import (hdf5_write_field, hdf5_write_column, hdf5_write_string_array,
                        point_array, column_array, snake_case, validate_display_groups,
                        vtkhdf_init_multiblock, vtkhdf_write_polydata_block, QUATERNION_ORDER)

'''


def _gen_helpers() -> str:
    return '''\
# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_gravity():
    """YADE gravity lives on NewtonIntegrator, not on O directly."""
    for eng in O.engines:
        if type(eng).__name__ == "NewtonIntegrator":
            g = eng.gravity
            return [g[0], g[1], g[2]]
    return [0.0, 0.0, 0.0]

def _sphere_volume(b):
    r = b.shape.radius
    return 4.0 / 3.0 * 3.141592653589793 * r**3

def _vec3(v):
    return np.array([v[0], v[1], v[2]], dtype=np.float64)

def _diag3(iv):
    """YADE inertia is a Vector3 of principal moments → diagonal 3x3."""
    return [[iv[0], 0.0, 0.0], [0.0, iv[1], 0.0], [0.0, 0.0, iv[2]]]

'''


def _gen_display_group_helpers(mapping: dict) -> str:
    """Generate the code-agnostic display group helpers.

    The DEM code has no display group: the user passes it to export_vtkhdf().
    The only code-specific part is the body id expression from the mapping.
    """
    body_id_expr = _lookup_mapping(mapping, "base_body", "body_id")
    return f'''\
# ---------------------------------------------------------------------------
# Display groups (set by export_vtkhdf arguments)
# ---------------------------------------------------------------------------

# default display groups (decision 18): spheres -> Points, every other shape -> Others
_DEFAULT_DISPLAY_GROUP_NAMES = ["Points", "Others"]
_DISPLAY_GROUP_NAMES = list(_DEFAULT_DISPLAY_GROUP_NAMES)
_DISPLAY_GROUP_SOURCE = None

def _display_group_names():
    """scene.display_group_names for the current export."""
    return list(_DISPLAY_GROUP_NAMES)

def _default_display_group(b):
    """Default rule: 0 (Points) for spheres, 1 (Others) for every other shape."""
    return 0 if _shape_name(b) == "sphere" else 1

def _display_group(b):
    """base_body.display_group of body b: from the dict {{body_id: index}} or the
    callable set by export_vtkhdf; 0 (the first group) otherwise."""
    src = _DISPLAY_GROUP_SOURCE
    if src is None:
        return 0
    if callable(src):
        return src(b)
    return src.get({body_id_expr}, 0)

def _collect(items, fields):
    """Evaluate every getter of fields on every item; a failing getter gives None."""
    cols = {{}}
    for name, _h, _mandatory, get in fields:
        vals = []
        for it in items:
            try: vals.append(get(it))
            except Exception: vals.append(None)
        cols[name] = vals
    return cols

'''


def _gen_scene_exporter(schema: Schema, mapping: dict) -> str:
    """Generate the _export_scene function from the scene class."""
    cls = schema.classes.get("scene")
    if not cls:
        return "# WARNING: scene class not found in schema\n"

    lines = [
        "def _export_scene(f):",
        '    """Write /ONDEM/Scene — generated from scene schema."""',
        '    grp = f.require_group("ONDEM/Scene")',
        "",
    ]

    scene_map = mapping.get("scene", {})
    for fld in cls.all_fields:
        expr = scene_map.get(fld.name)
        if not expr:
            lines.append(f'    # UNMAPPED: {fld.name} ({fld.type_str})')
            continue

        tag = "[mandatory]" if fld.mandatory else "[optional]" if fld.optional else ""
        lines.append(f"    # {tag} {fld.name}: {fld.type_str} {fld.units}")

        line = _hdf5_write_expr(fld, expr, "grp")
        lines.append("    " + line)
        lines.append("")

    extra = mapping.get("_extra_scene_fields", {})
    if extra:
        lines.append("    # not in the schema yet (provisional, mapping _extra_scene_fields)")
    for fname, expr in extra.items():
        h = _EXTRA_SCENE_FIELD_TYPES.get(fname, "scalar_float")
        lines.append(f'    hdf5_write_field(grp, "{fname}", "{h}", {expr}, scalar_as_dataset=False)')
    if extra:
        lines.append("")

    return "\n".join(lines) + "\n"


# HDF5 types of scene fields that are not in the schema yet (mapping "_extra_scene_fields")
_EXTRA_SCENE_FIELD_TYPES = {"iteration": "scalar_int"}


def _gen_materials_exporter(schema: Schema, mapping: dict) -> str:
    """Generate _export_materials: one group per material with the fields of the
    schema classes listed in the mapping ("_material_classes")."""
    mat_classes = mapping.get("_material_classes", ["base_material"])
    note = mapping.get("_material_classes_note")

    lines = [
        "def _export_materials(f):",
        '    """Write /ONDEM/Materials — generated from materials schema."""',
        '    mat_grp = f.require_group("ONDEM/Materials")',
        "    seen_ids = set()",
        "    for b in O.bodies:",
        "        if b is None or b.material is None: continue   # clump bodies have no material",
        "        mat = b.material",
        "        if mat.id in seen_ids: continue",
        "        seen_ids.add(mat.id)",
        "        g = mat_grp.create_group(str(mat.id))",
        f'        g.attrs["schema_classes"] = {", ".join(mat_classes)!r}',
    ]
    if note:
        lines.append(f'        g.attrs["provisional"] = {note!r}')
    lines += [
        "",
        "        # Extra YADE-specific attributes (not in schema but useful)",
    ]

    extra = mapping.get("_extra_material_attributes", {})
    _extra_str_fields = {"label", "material_type", "yade_material_type"}
    for fname, expr in extra.items():
        if fname in _extra_str_fields:
            lines.append(f'        try: g.create_dataset("{fname}", data=str({expr}).encode("utf-8"))')
        else:
            lines.append(f'        try: g.create_dataset("{fname}", data=np.float64({expr}))')
        lines.append(f'        except: pass')
    lines.append("")

    # For each material class, emit its fields including inherited ones
    # (strict lookup: class.field only)
    already_emitted = set()
    for cls_name in mat_classes:
        cls = schema.classes.get(cls_name)
        if not cls:
            lines.append(f"        # WARNING: schema class {cls_name} not found")
            continue
        lines.append(f"        # --- {cls_name}: {cls.docstring} ---")
        for fld in cls.all_fields:
            if fld.name in already_emitted:
                continue
            already_emitted.add(fld.name)
            expr = mapping.get(cls_name, {}).get(fld.name)
            if not expr:
                lines.append(f'        # UNMAPPED: {fld.name}')
                continue
            tag = "[mandatory]" if fld.mandatory else "[optional]"
            lines.append(f"        # {tag} {fld.name}: {fld.type_str} {fld.units}")
            lines.append(f"        try:")
            line = _hdf5_write_expr(fld, expr, "g", scalar_as_dataset=True)
            lines.append("            " + line)
            lines.append(f"        except Exception as _e:")
            if fld.mandatory:
                lines.append(f'            print(f"[export_vtkhdf] Warning: material {{mat.id}}: mandatory field {fld.name} not written ({{_e}})")')
            else:
                lines.append(f'            pass  # field not available for this material type')
            lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Bodies: one VTKHDF block per display group, every per-body field in the blocks
# ---------------------------------------------------------------------------
# Decision 12 (2 October 2026): every per-body field is PointData of the block
# the body is in; /ONDEM keeps the scene, the materials and the interactions.
# Fields that do not apply to a body are NaN (floats) or -1 (integers).

# Schema classes that hold per-body data (fields are merged in this order)
_BODY_CLASSES = ["base_body", "base_state", "thermal", "liquid_film"]

# Schema shape classes whose fields are written (NaN / -1 for other shapes)
_SHAPE_CLASSES = ["sphere", "box", "polyhedron", "clump"]

# HDF5 types of per-body fields that are not in the schema yet (mapping
# "_extra_body_fields"; provisional, not decided)
_EXTRA_BODY_FIELD_TYPES = {
    "group_mask": "scalar_int", "is_damped": "scalar_bool",
    "angular_momentum": "vector3", "density_scaling": "scalar_float",
}

# HDF5 types of the fields of shapes that are not in the schema yet (mapping
# "_extra_shapes"; written as <shape>_<field>, non-normative)
_EXTRA_SHAPE_FIELD_TYPES = {
    "axis": "scalar_int", "sense": "scalar_int",
    "normal": "vector3", "vertices": "matrix3",
}

_WRITABLE = ("scalar_float", "scalar_int", "scalar_bool", "vector3", "quaternion", "matrix3")


def _field_entry(fld: FieldDef, expr: str, var: str, cls_name: str, mandatory: bool = None) -> list:
    tag = "[mandatory]" if fld.mandatory else "[optional]" if fld.optional else ""
    m = fld.mandatory if mandatory is None else mandatory
    return [
        f"    # {tag} {cls_name}.{fld.name}: {fld.type_str} {fld.units}".rstrip(),
        f'    ("{fld.name}", "{fld.hdf5_type}", {m}, lambda {var}: {expr}),',
    ]


def _gen_bodies_exporter(schema: Schema, mapping: dict) -> str:
    """Generate _export_bodies: one PolyData block per display group with every per-body field."""
    collections = mapping.get("_collections", {})
    bodies_expr = collections.get("bodies", "[]")
    group_expr = _lookup_mapping(mapping, "base_body", "display_group") or "0"
    shape_type_expr = mapping.get("_shape_type", "None")
    shape_groups = mapping.get("_shape_groups", {})
    shape_names = mapping.get("_shape_names", [])
    extra_shapes = mapping.get("_extra_shapes", {})

    lines = [
        "# Per-body fields: (name, hdf5 type, always written, getter).",
        "# Generated from the schema; getters are the mapping expressions. A field that is",
        "# not always written is written when at least one body has a value.",
        "_BODY_FIELDS = [",
    ]
    seen = set()
    for cls_name in _BODY_CLASSES:
        cls = schema.classes.get(cls_name)
        if not cls:
            lines.append(f"    # WARNING: schema class {cls_name} not found")
            continue
        for fld in cls.all_fields:
            if fld.name in seen or fld.name == "display_group":
                continue
            seen.add(fld.name)
            if fld.hdf5_type == "unknown":
                lines.append(f"    # SKIPPED {cls_name}.{fld.name}: nested type {fld.type_str}")
                continue
            expr = _lookup_mapping(mapping, cls_name, fld.name)
            if not expr:
                lines.append(f"    # UNMAPPED {cls_name}.{fld.name}")
                continue
            lines += _field_entry(fld, expr, "b", cls_name)
    lines.append("    # shape fields: NaN / -1 for bodies of other shapes")
    for cls_name in _SHAPE_CLASSES:
        cls = schema.classes.get(cls_name)
        for fld in (cls.fields if cls else []):
            if fld.name in seen:
                continue
            seen.add(fld.name)
            expr = _lookup_mapping(mapping, cls_name, fld.name)
            if not expr:
                lines.append(f"    # UNMAPPED {cls_name}.{fld.name}")
                continue
            if fld.hdf5_type not in _WRITABLE:
                lines.append(f"    # SKIPPED {cls_name}.{fld.name}: type {fld.type_str}, variable length "
                             f"per body (see the shapes proposal)")
                continue
            lines += _field_entry(fld, expr, "b", cls_name, mandatory=False)
    for group_name, fields in extra_shapes.items():
        lines.append(f"    # {group_name}: shape not in the schema yet (non-normative)")
        for fname, expr in fields.items():
            h = _EXTRA_SHAPE_FIELD_TYPES.get(fname, "scalar_float")
            lines.append(f'    ("{group_name}_{fname}", "{h}", False, lambda b: {expr}),')
    extra_body = mapping.get("_extra_body_fields", {})
    if extra_body:
        lines.append("    # not in the schema (provisional, not decided; mapping _extra_body_fields)")
    for fname, expr in extra_body.items():
        h = _EXTRA_BODY_FIELD_TYPES.get(fname, "scalar_float")
        lines.append(f'    ("{fname}", "{h}", True, lambda b: {expr}),')
    lines.append("]")
    lines.append("")
    lines.append("# code shape type -> schema shape name, and scene.shape_names (fixed list from the")
    lines.append("# mapping; readers map shapes by name through the list, never by a fixed index)")
    lines.append(f"_SHAPE_GROUPS = {shape_groups!r}")
    lines.append(f"_SHAPE_NAMES = {shape_names!r}")
    lines.append("")
    lines.append("def _shape_names():")
    lines.append('    """scene.shape_names."""')
    lines.append("    return list(_SHAPE_NAMES)")
    lines.append("")
    lines.append("def _shape_name(b):")
    lines.append('    """Schema shape name of body b; "other" for shapes not supported yet."""')
    lines.append(f"    try: return _SHAPE_GROUPS.get({shape_type_expr}, \"other\")")
    lines.append('    except Exception: return "other"')
    lines.append("")
    lines.append("def _shape_type_index(b):")
    lines.append('    """base_body.shape_type: index of the shape name in scene.shape_names."""')
    lines.append("    return _SHAPE_NAMES.index(_shape_name(b))")
    lines.append("")
    lines.append("def _code_shape_type(b):")
    lines.append(f"    try: return str({shape_type_expr})")
    lines.append('    except Exception: return "?"')
    lines.append("")

    lines += [
        "def _export_bodies(f):",
        '    """Write the bodies: one PolyData block per display group in /VTKHDF, every',
        '    per-body field as PointData; Points = positions (float64)."""',
        f"    bodies = {bodies_expr}",
        "    names = _display_group_names()",
        "    cols = _collect(bodies, _BODY_FIELDS)",
        '    body_ids = cols["body_id"]',
        "    if None in body_ids or len(set(body_ids)) != len(body_ids):",
        '        raise ValueError("[export_vtkhdf] body ids must be unique and defined")',
        f"    groups = [{group_expr} for b in bodies]",
        "    validate_display_groups(names, dict(zip(body_ids, groups)))",
        "    other = sorted({_code_shape_type(b) for b in bodies if _shape_name(b) == 'other'})",
        "    if other:",
        '        print(f"[export_vtkhdf] Warning: shapes {other} are not supported by the format yet; "',
        '              f"they are written with shape \'other\' and cannot be restored")',
        "",
        "    # the same arrays in every block: a field is written when it is always written",
        "    # or when at least one body has a value; NaN / -1 elsewhere",
        "    types = {name: h for name, h, _m, _g in _BODY_FIELDS}",
        '    written = [name for name, h, always, _g in _BODY_FIELDS if name not in ("position", "body_id")',
        "               and (always or any(v is not None for v in cols[name]))]",
        "",
        "    vtkhdf_init_multiblock(f)",
        "    for gi, name in enumerate(names):",
        "        idx = [k for k, g in enumerate(groups) if g == gi]",
        "        sel = lambda col: [col[k] for k in idx]",
        "        vtkhdf_write_polydata_block(",
        "            f, name, sel(body_ids),",
        '            points=point_array(sel(cols["position"]), 3),',
        "            point_data={n: column_array(sel(cols[n]), types[n]) for n in written},",
        '            point_data_attrs={n: {"order": QUATERNION_ORDER} for n in written if types[n] == "quaternion"},',
        "        )",
        "",
        "    return len(bodies)",
        "",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Interactions: /ONDEM/Interactions/<type>
# ---------------------------------------------------------------------------

# Schema interaction classes whose fields are collected (merged in this order)
_INTERACTION_CLASSES = ["base_interaction", "normal", "shear", "shear_linear", "normal_linear", "normal_hertz",
                        "linear_frictional_3D"]

# HDF5 types of interaction fields that are not in the schema
_EXTRA_INTERACTION_TYPES = {
    "contact_point": "vector3", "overlap": "scalar_float",
    "reference_radius_1": "scalar_float", "reference_radius_2": "scalar_float",
    "geom_type": "string", "phys_type": "string",
    "normal_stiffness": "scalar_float", "shear_stiffness": "scalar_float",
    "frictional_dissipation": "scalar_float",
}


def _gen_interactions_exporter(schema: Schema, mapping: dict) -> str:
    """Generate _export_interactions: one group per interaction type."""
    collections = mapping.get("_collections", {})
    intrs_expr = collections.get("interactions", "[]")
    type_expr = mapping.get("_interaction_type", "'interaction'")

    lines = [
        "# Per-interaction fields: (name, hdf5 type, mandatory, getter).",
        "_INTERACTION_FIELDS = [",
    ]
    seen = set()
    for cls_name in _INTERACTION_CLASSES:
        cls = schema.classes.get(cls_name)
        if not cls:
            lines.append(f"    # WARNING: schema class {cls_name} not found")
            continue
        for fld in cls.all_fields:
            if fld.name in seen:
                continue
            seen.add(fld.name)
            expr = _lookup_mapping(mapping, cls_name, fld.name)
            if not expr:
                lines.append(f"    # UNMAPPED {cls_name}.{fld.name}")
                continue
            lines += _field_entry(fld, expr, "i", cls_name)
    for section in ("_interaction_geometry", "_extra_interaction_attributes"):
        lines.append(f"    # not in the schema (mapping {section})")
        for fname, expr in mapping.get(section, {}).items():
            if fname in seen:
                continue
            seen.add(fname)
            h = _EXTRA_INTERACTION_TYPES.get(fname, "scalar_float")
            lines.append(f'    ("{fname}", "{h}", False, lambda i: {expr}),')
    lines.append("]")
    lines.append("")

    lines += [
        "def _interaction_type(i):",
        f"    try: return snake_case(str({type_expr}))",
        '    except Exception: return "unknown"',
        "",
        "def _export_interactions(f):",
        '    """Write /ONDEM/Interactions/<type>/: one group per interaction type (snake_case)."""',
        '    ig_root = f.require_group("ONDEM/Interactions")',
        f"    intrs = {intrs_expr}",
        "    by_type = {}",
        "    for i in intrs:",
        "        by_type.setdefault(_interaction_type(i), []).append(i)",
        "",
        "    for itype in sorted(by_type):",
        "        members = by_type[itype]",
        "        ig = ig_root.create_group(itype)",
        '        ig.attrs["count"] = len(members)',
        "        cols = _collect(members, _INTERACTION_FIELDS)",
        "        for name, h, mandatory, _get in _INTERACTION_FIELDS:",
        "            vals = cols[name]",
        "            if not mandatory and all(v is None for v in vals):",
        "                continue",
        "            hdf5_write_column(ig, name, vals, h)",
        "",
        "    return len(intrs)",
        "",
    ]
    return "\n".join(lines) + "\n"


def _gen_main_function(schema_dir: str, mapping_path: str, mapping: dict) -> str:
    time_expr = mapping.get("scene", {}).get("time", "float('nan')")
    refuse_code = "".join(f"    if {expr}:\n        raise ValueError({('[export_vtkhdf] ' + msg)!r})\n"
                          for msg, expr in mapping.get("_refuse_if", {}).items())
    return f'''\
# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def export_vtkhdf(filename, display_group_names=None, display_group=None):
    """Export the current simulation state to an ON-DEM VTKHDF file (one timestep).

    Generated from schema: {schema_dir}
    Mapping file:          {mapping_path}

    Parameters
    ----------
    filename : str
        Output file path (should end in .vtkhdf or .hdf).
    display_group_names : list of str, optional
        scene.display_group_names: one VTKHDF block per name, in this order.
    display_group : dict or callable, optional
        base_body.display_group of each body, an index into display_group_names:
        a dict {{body_id: index}} (bodies not in the dict get 0) or a callable
        body -> index. Requires display_group_names.

    Neither given: the default groups ['Points', 'Others'], spheres in Points and
    every other shape in Others. Names given without display_group: every body
    in the first group. Every group gets a block, also when it is empty.

    Raises ValueError (and writes no file) if display_group is given without
    display_group_names, if a name or an index is invalid, or if the scene
    cannot be written completely (mapping "_refuse_if", e.g. a periodic cell).
    """
{refuse_code}    global _DISPLAY_GROUP_NAMES, _DISPLAY_GROUP_SOURCE
    if display_group is not None and display_group_names is None:
        raise ValueError("[export_vtkhdf] display_group was given without display_group_names: "
                         "give the names of the groups it indexes (the defaults 'Points' / 'Others' "
                         "only go with the default rule)")
    if display_group_names is None:
        _DISPLAY_GROUP_NAMES = list(_DEFAULT_DISPLAY_GROUP_NAMES)
        _DISPLAY_GROUP_SOURCE = _default_display_group
    else:
        _DISPLAY_GROUP_NAMES = list(display_group_names)
        _DISPLAY_GROUP_SOURCE = display_group

    try:
        with h5py.File(filename, "w") as f:

            # 1. Bodies: /VTKHDF blocks (one per display group) + /ONDEM/Bodies
            n_bodies = _export_bodies(f)

            # 2. Scene metadata (includes display_group_names)
            _export_scene(f)

            # 3. Materials
            _export_materials(f)

            # 4. Interactions
            n_intrs = _export_interactions(f)

            # Top-level metadata
            f.attrs["file_format"]         = "ON-DEM VTKHDF"
            f.attrs["file_format_version"] = "0.2-draft"
            f.attrs["schema_dir"]          = "{schema_dir}"
            f.attrs["mapping_file"]        = "{mapping_path}"
    except Exception:
        # do not leave a half-written file behind
        if os.path.exists(filename):
            os.remove(filename)
        raise

    print(f"[export_vtkhdf] Exported {{n_bodies}} bodies in {{len(_DISPLAY_GROUP_NAMES)}} display group(s), "
          f"{{n_intrs}} interactions at t={{{time_expr}:.6g}} to \'{{filename}}\'")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "output.vtkhdf"
    export_vtkhdf(out)
'''


# ---------------------------------------------------------------------------
# Top-level generator
# ---------------------------------------------------------------------------

def generate(schema_dir: str, mapping_path: str, out_path: str):
    print(f"[codegen_yade] Parsing schema from: {schema_dir}")
    schema = parse_schema_dir(schema_dir)

    print(f"[codegen_yade] Loading mapping from: {mapping_path}")
    mapping = _load_mapping(mapping_path)

    print(f"[codegen_yade] Generating exporter...")

    sections = [
        _gen_header(schema_dir, mapping_path),
        _gen_helpers(),
        _gen_display_group_helpers(mapping),
        _gen_scene_exporter(schema, mapping),
        _gen_materials_exporter(schema, mapping),
        _gen_bodies_exporter(schema, mapping),
        _gen_interactions_exporter(schema, mapping),
        _gen_main_function(schema_dir, mapping_path, mapping),
    ]

    output = "\n".join(sections)

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(output)

    print(f"[codegen_yade] Written to: {out_path}")
    print(f"[codegen_yade] Lines: {output.count(chr(10))}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate YADE→VTKHDF exporter from ON-DEM schema")
    parser.add_argument("schema_dir",
        help="Directory containing ON-DEM schema .py files")
    parser.add_argument("--mapping", default="yade_mapping.json",
        help="Path to YADE field mapping JSON (default: yade_mapping.json)")
    parser.add_argument("--out", default="export_yade_vtkhdf.py",
        help="Output file path (default: export_yade_vtkhdf.py)")

    args = parser.parse_args()
    generate(args.schema_dir, args.mapping, args.out)
