"""
codegen_dem.py
ON-DEM WG3 - DEM Exporter Code Generator

Reads the ON-DEM schema (parsed by schema_parser.py) and a DEM field
mapping (e.g., yade_mapping.json) and emits a complete export_dem_vtkhdf.py.

Usage:
    python codegen_dem.py <schema_dir> [--mapping dem_mapping.json] [--out export_dem_vtkhdf.py]

Example:
    python codegen_dem.py ./schema --mapping yade_mapping.json --out export_yade_vtkhdf.py
"""

import json
import os
import sys
import argparse
from textwrap import indent, dedent
from datetime import date

from schema_parser import parse_schema_dir, Schema, ClassDef, FieldDef


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_mapping(mapping_path: str) -> dict:
    with open(mapping_path) as f:
        return json.load(f)


def _lookup_mapping(mapping: dict, class_name: str, field_name: str):
    """Look up the YADE expression for a schema field.
    Precedence: class.field > field fallback.
    Returns None if not found.
    """
    cls_entry = mapping.get(class_name, {})
    if field_name in cls_entry:
        return cls_entry[field_name]
    # Search all class entries for the field (less specific fallback)
    for k, v in mapping.items():
        if k.startswith("_"):
            continue
        if isinstance(v, dict) and field_name in v:
            return v[field_name]
    return None


def _hdf5_write_expr(field: FieldDef, yade_expr: str, group_var: str,
                     scalar_as_dataset: bool = False) -> str:
    """Return a code line to write one field using hdf5_utils.hdf5_write_field."""
    n = field.name
    h = field.hdf5_type
    return f'hdf5_write_field({group_var}, "{n}", "{h}", {yade_expr}, scalar_as_dataset={scalar_as_dataset})'


# ---------------------------------------------------------------------------
# Section generators
# ---------------------------------------------------------------------------

def _gen_header(schema_dir: str, mapping_path: str) -> str:
    return f'''\
"""
export_yade_vtkhdf.py
ON-DEM WG3 - YADE to VTKHDF exporter

AUTO-GENERATED by codegen_yade.py on {date.today().isoformat()}
  Schema dir : {schema_dir}
  Mapping    : {mapping_path}

DO NOT EDIT MANUALLY - re-run the generator to update.

Usage (inside YADE or from yadedaily -x):
    from export_yade_vtkhdf import export_vtkhdf
    export_vtkhdf("output.vtkhdf")

Periodic engine usage:
    O.engines += [PyRunner(
        command='export_vtkhdf("sim_%04d.vtkhdf" % O.iter)',
        iterPeriod=1000)]
"""

import numpy as np
import h5py
import os
import sys

from hdf5_utils import hdf5_write_field, hdf5_write_scalar_array, hdf5_write_vector3_array, hdf5_write_quaternion_array, hdf5_write_matrix3_array, hdf5_write_string_array

'''


def _gen_helpers() -> str:
    return '''\
# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_gravity():
    """YADE gravity lives on NewtonIntegrator, not on O directly."""
    for eng in O.engines:
        if type(eng).__name__ == "NewtonIntegrator":
            g = eng.gravity
            return [g[0], g[1], g[2]]
    return [0.0, 0.0, 0.0]

def _sphere_volume(b):
    r = b.shape.radius
    return 4.0 / 3.0 * 3.141592653589793 * r**3

def _vec3(v):
    return np.array([v[0], v[1], v[2]], dtype=np.float64)

def _quat(q):
    """YADE: q[0]=w → store as [x,y,z,w]"""
    return np.array([q[1], q[2], q[3], q[0]], dtype=np.float64)

def _mat3_flat(iv):
    """YADE inertia is a Vector3 of principal moments → diagonal 3x3, row-major."""
    return np.array([iv[0],0,0, 0,iv[1],0, 0,0,iv[2]], dtype=np.float64)

'''


def _gen_scene_exporter(schema: Schema, mapping: dict) -> str:
    """Generate the _export_scene function from the scene class."""
    cls = schema.classes.get("scene")
    if not cls:
        return "# WARNING: scene class not found in schema\n"

    lines = [
        "def _export_scene(f):",
        '    """Write /ONDEM/Scene — generated from scene schema."""',
        '    grp = f.require_group("ONDEM/Scene")',
        "",
    ]

    scene_map = mapping.get("scene", {})
    for fld in cls.all_fields:
        expr = scene_map.get(fld.name)
        if not expr:
            lines.append(f'    # UNMAPPED: {fld.name} ({fld.type_str})')
            continue

        tag = "[mandatory]" if fld.mandatory else "[optional]" if fld.optional else ""
        lines.append(f"    # {tag} {fld.name}: {fld.type_str} {fld.units}")

        line = _hdf5_write_expr(fld, expr, "grp")
        lines.append("    " + line)
        lines.append("")

    return "\n".join(lines) + "\n"


def _gen_materials_exporter(schema: Schema, mapping: dict) -> str:
    """Generate _export_materials collecting all material_* classes."""
    # Find all material classes in order of inheritance
    mat_classes = [
        "material_general",
        "material_spring_constants",
        "material_elastic_constants",
        "material_visco_elastic_constants_COR",
        "material_visco_elastic_variable_COR",
    ]
    # Only keep those that exist in schema
    mat_classes = [c for c in mat_classes if c in schema.classes]

    lines = [
        "def _export_materials(f):",
        '    """Write /ONDEM/Materials — generated from materials schema."""',
        '    mat_grp = f.require_group("ONDEM/Materials")',
        "    seen_ids = set()",
        "    for b in O.bodies:",
        "        if b is None: continue",
        "        mat = b.material",
        "        if mat.id in seen_ids: continue",
        "        seen_ids.add(mat.id)",
        "        g = mat_grp.create_group(str(mat.id))",
        "",
        "        # Extra YADE-specific attributes (not in schema but useful)",
    ]

    extra = mapping.get("_extra_material_attributes", {})
    _extra_str_fields = {"label", "material_type", "yade_material_type"}
    for fname, expr in extra.items():
        if fname in _extra_str_fields:
            lines.append(f'        try: g.create_dataset("{fname}", data=str({expr}).encode("utf-8"))')
        else:
            lines.append(f'        try: g.create_dataset("{fname}", data=np.float64({expr}))')
        lines.append(f'        except: pass')
    lines.append("")

    # For each material class, emit its fields
    already_emitted = set()
    for cls_name in mat_classes:
        cls = schema.classes[cls_name]
        lines.append(f"        # --- {cls_name}: {cls.docstring} ---")
        for fld in cls.fields:
            if fld.name in already_emitted:
                continue
            already_emitted.add(fld.name)
            expr = _lookup_mapping(mapping, cls_name, fld.name)
            if not expr:
                lines.append(f'        # UNMAPPED: {fld.name}')
                continue
            tag = "[mandatory]" if fld.mandatory else "[optional]"
            lines.append(f"        # {tag} {fld.name}: {fld.type_str} {fld.units}")
            lines.append(f"        try:")
            line = _hdf5_write_expr(fld, expr, "g", scalar_as_dataset=True)
            lines.append("            " + line)
            lines.append(f"        except Exception as _e:")
            lines.append(f'            pass  # field not available for this material type')
            lines.append("")

    return "\n".join(lines) + "\n"


def _gen_spheres_exporter(schema: Schema, mapping: dict) -> str:
    """Generate _export_bodies writing bodies separated by shape type to /ONDEM/Bodies/."""
    state_cls  = schema.classes.get("state")
    sphere_cls = schema.classes.get("sphere")
    body_cls   = schema.classes.get("body")

    # Shape types to separate
    shape_types = ['Sphere', 'Box', 'Polyhedron', 'Wall', 'Facet']

    # Collect all fields we want per body
    # body fields + state fields + shape-specific fields
    all_particle_fields = []
    seen = set()

    for cls_name in ["body", "state", "sphere", "box", "polyhedron"]:
        cls = schema.classes.get(cls_name)
        if not cls:
            continue
        for fld in cls.all_fields:
            if fld.name in seen:
                continue
            seen.add(fld.name)
            all_particle_fields.append((cls_name, fld))

    # Build collection loop
    lines = [
        "def _export_bodies(f):",
        '    """Write bodies separated by shape type to /ONDEM/Bodies/ — generated from schema."""',
        "",
        '    bodies_grp = f.require_group("ONDEM/Bodies")',
        "",
        f"    shape_types = {shape_types}",
        "",
        "    for shape_type in shape_types:",
        "        bodies = [b for b in O.bodies if b is not None and type(b.shape).__name__ == shape_type]",
        "        if not bodies: continue",
        "",
        '        bg = bodies_grp.require_group(shape_type)',
        "        bg.attrs['count'] = len(bodies)",
        "",
        "        # --- Collect body data ---",
    ]

    # Declare accumulator lists for each field
    for cls_name, fld in all_particle_fields:
        expr = _lookup_mapping(mapping, cls_name, fld.name)
        if not expr:
            continue
        lines.append(f"        _{fld.name}_list = []")

    lines += [
        "",
        "        for b in bodies:",
        "",
    ]

    for cls_name, fld in all_particle_fields:
        expr = _lookup_mapping(mapping, cls_name, fld.name)
        if not expr:
            continue
        lines.append(f"            try: _{fld.name}_list.append({expr})")
        lines.append(f"            except: _{fld.name}_list.append(None)")

    lines += [
        "",
        "    N = len(_body_id_list)",
        "    if N == 0:",
        '        print("[export_vtkhdf] Warning: no sphere bodies found")',
        "        return 0",
        "",
        "    # --- Write /VTKHDF/ VTK PolyData structure ---",
        '    vtk = f.require_group("VTKHDF")',
        '    _typeStr = "PolyData".encode("ascii")',
        '    vtk.attrs.create("Type", _typeStr, dtype=h5py.string_dtype("ascii", len(_typeStr)))',
        '    vtk.attrs.create("Version", data=np.array([1, 0], dtype=np.int64))',
        "",
        "    # Points = sphere centres",
        "    pos_arr = np.array([[p[0],p[1],p[2]] for p in _position_list], dtype=np.float64)",
        '    vtk.create_dataset("Points", data=pos_arr)',
        '    vtk.create_dataset("NumberOfPoints", data=np.array([N], dtype=np.int64))',
        "",
        "    # Empty cell structures (required by VTK HDF spec for PolyData)",
        '    for _sec in ["Vertices","Lines","Polygons","Strips"]:',
        '        _sg = vtk.require_group(_sec)',
        '        _sg.create_dataset("NumberOfCells",           data=np.array([0], dtype=np.int64))',
        '        _sg.create_dataset("NumberOfConnectivityIds", data=np.array([0], dtype=np.int64))',
        '        _sg.create_dataset("Offsets",                 data=np.array([0, 0], dtype=np.int64))',
        '        _sg.create_dataset("Connectivity",            data=np.zeros(0,   dtype=np.int64))',
        "",
        '    pd = vtk.require_group("PointData")',
        '    pd.attrs["Scalars"] = "radius".encode("ascii")',  # default display hint for ParaView
        "",
        "    # --- Write per-particle datasets ---",
    ]

    # Emit write calls for each collected field
    for cls_name, fld in all_particle_fields:
        expr = _lookup_mapping(mapping, cls_name, fld.name)
        if not expr:
            continue
        n = fld.name
        h = fld.hdf5_type
        tag = "[mandatory]" if fld.mandatory else "[optional]"
        lines.append(f"        # {tag} {n}: {fld.type_str} {fld.units}")

        if h in ("scalar_float",):
            lines.append(f'        hdf5_write_scalar_array(bg, "{n}", _{n}_list, np.float64)')
        elif h in ("scalar_int",):
            lines.append(f'        hdf5_write_scalar_array(bg, "{n}", _{n}_list, np.int32)')
        elif h in ("scalar_bool",):
            lines.append(f'        hdf5_write_scalar_array(bg, "{n}", _{n}_list, np.int8)')
        elif h == "vector3":
            lines.append(f'        hdf5_write_vector3_array(bg, "{n}", _{n}_list)')
        elif h == "quaternion":
            lines.append(f'        hdf5_write_quaternion_array(bg, "{n}", _{n}_list)')
        elif h == "matrix3":
            lines.append(f'        hdf5_write_matrix3_array(bg, "{n}", _{n}_list)')
        else:
            lines.append(f'        # SKIPPED dataset for {n} (type={h})')
        lines.append("")

    lines.append("")
    lines.append("    # --- Unified VTK PolyData for all bodies ---")
    lines.append("    bodies = [b for b in O.bodies if b is not None]")
    lines.append("    N = len(bodies)")
    lines.append("    if N == 0:")
    lines.append('        print("[export_vtkhdf] Warning: no bodies found")')
    lines.append("        return 0")
    lines.append("")
    lines.append('    vtk = f.require_group("VTKHDF")')
    lines.append('    vtk.attrs.create("Type",    data=np.bytes_("PolyData"))')
    lines.append('    vtk.attrs.create("Version", data=np.array([2, 0], dtype=np.int64))')
    lines.append("")
    lines.append("    # Points = body centres")
    lines.append("    positions = [b.state.pos for b in bodies]")
    lines.append("    hdf5_write_vector3_array(vtk, \"Points\", positions)")
    lines.append('    vtk.create_dataset("NumberOfPoints", data=np.array([N], dtype=np.int64))')
    lines.append("")
    lines.append("    # Empty cell structures (required by VTK HDF spec for PolyData)")
    lines.append('    for _sec in ["Verts","Lines","Polygons","Strips"]:')
    lines.append('        _sg = vtk.require_group(_sec)')
    lines.append('        _sg.create_dataset("NumberOfCells",           data=np.array([0], dtype=np.int64))')
    lines.append('        _sg.create_dataset("NumberOfConnectivityIds", data=np.array([0], dtype=np.int64))')
    lines.append('        _sg.create_dataset("Offsets",                 data=np.array([0], dtype=np.int64))')
    lines.append('        _sg.create_dataset("Connectivity",            data=np.array([], dtype=np.int64))')
    lines.append("")
    lines.append('    pd = vtk.require_group("PointData")')
    lines.append("")
    lines.append("    # Shape types")
    lines.append("    shape_types_list = [type(b.shape).__name__ for b in bodies]")
    lines.append('    hdf5_write_string_array(pd, "shape_type", shape_types_list)')
    lines.append("")
    lines.append("    return N")
    lines.append("")

    return "\n".join(lines) + "\n"


def _gen_interactions_exporter(schema: Schema, mapping: dict) -> str:
    """Generate _export_interactions from interaction schema classes, separated by type."""

    # Interaction types to separate
    intr_types = ['Normal', 'Shear', 'NormalLinear', 'ShearLinear', 'NormalHertz', 'Intr', 'Intr3D']

    # Fields to collect from schema interaction classes
    intr_classes = ["intr", "normal", "shear", "shear_linear", "normal_linear", "normal_hertz"]
    intr_classes = [c for c in intr_classes if c in schema.classes]

    all_intr_fields = []
    seen = set()
    for cls_name in intr_classes:
        cls = schema.classes[cls_name]
        for fld in cls.all_fields:
            if fld.name in seen:
                continue
            seen.add(fld.name)
            all_intr_fields.append((cls_name, fld))

    # Extra geometry fields from mapping (not in schema classes directly)
    geom_extras = mapping.get("_interaction_geometry", {})
    extra_intr = mapping.get("_extra_interaction_attributes", {})

    lines = [
        "def _export_interactions(f):",
        '    """Write /ONDEM/Interactions — generated from interaction schema, separated by type."""',
        '    ig_root = f.require_group("ONDEM/Interactions")',
        "",
        f"    intr_types = {intr_types}",
        "",
        "    for phys_type in intr_types:",
        "        intrs = [i for i in O.interactions if i.isReal and type(i.phys).__name__ == phys_type]",
        "        if not intrs: continue",
        "",
        '        ig = ig_root.require_group(phys_type)',
        "        ig.attrs['count'] = len(intrs)",
        "",
        "        # --- Accumulate per-interaction data ---",
    ]

    # Schema fields
    for cls_name, fld in all_intr_fields:
        expr = _lookup_mapping(mapping, cls_name, fld.name)
        if not expr:
            continue
        lines.append(f"        _{fld.name}_list = []")

    # Geometry extras
    for fname in geom_extras:
        lines.append(f"        _{fname}_list = []")

    # Extra attributes
    for fname in extra_intr:
        lines.append(f"        _{fname}_list = []")

    lines += [
        "",
        "        for i in intrs:",
        "",
    ]

    for cls_name, fld in all_intr_fields:
        expr = _lookup_mapping(mapping, cls_name, fld.name)
        if not expr:
            continue
        lines.append(f"            try: _{fld.name}_list.append({expr})")
        lines.append(f"            except: _{fld.name}_list.append(None)")

    for fname, expr in geom_extras.items():
        lines.append(f"            try: _{fname}_list.append({expr})")
        lines.append(f"            except: _{fname}_list.append(None)")

    for fname, expr in extra_intr.items():
        lines.append(f"            try: _{fname}_list.append({expr})")
        lines.append(f"            except: _{fname}_list.append(None)")

    lines.append("")
    lines.append("        # --- Write datasets ---")

    def _emit_dataset(n, h, lines):
        if h in ("scalar_float",):
            lines.append(f'        hdf5_write_scalar_array(ig, "{n}", _{n}_list, np.float64)')
        elif h in ("scalar_int",):
            lines.append(f'        hdf5_write_scalar_array(ig, "{n}", _{n}_list, np.int32)')
        elif h in ("scalar_bool",):
            lines.append(f'        hdf5_write_scalar_array(ig, "{n}", _{n}_list, np.int8)')
        elif h == "string":
            lines.append(f'        hdf5_write_string_array(ig, "{n}", _{n}_list)')
        elif h == "vector3":
            lines.append(f'        hdf5_write_vector3_array(ig, "{n}", _{n}_list)')
        elif h == "quaternion":
            lines.append(f'        hdf5_write_quaternion_array(ig, "{n}", _{n}_list)')
        else:
            lines.append(f'        # SKIPPED {n} (type={h})')

    for cls_name, fld in all_intr_fields:
        expr = _lookup_mapping(mapping, cls_name, fld.name)
        if not expr:
            continue
        lines.append(f"        # {fld.name}: {fld.type_str} {fld.units}")
        _emit_dataset(fld.name, fld.hdf5_type, lines)
        lines.append("")

    # Geometry extras (all Vector3 or scalar float)
    geom_types = {
        "contact_point": "vector3", "overlap": "scalar_float",
        "reference_radius_1": "scalar_float", "reference_radius_2": "scalar_float"
    }
    for fname in geom_extras:
        h = geom_types.get(fname, "scalar_float")
        _emit_dataset(fname, h, lines)
        lines.append("")

    # Extra attributes (scalars + vectors)
    extra_types = {
        "geom_type": "string", "phys_type": "string",
        "normal_stiffness": "scalar_float", "shear_stiffness": "scalar_float",
        "friction_coefficient_interaction": "scalar_float",
        "normal_damping_ratio": "scalar_float", "shear_damping_ratio": "scalar_float",
        "isSliding": "scalar_int",
        "shear_force_elastic": "vector3", "shear_force_viscous": "vector3",
        "normal_force_viscous": "scalar_float",
    }
    for fname, expr in extra_intr.items():
        h = extra_types.get(fname, "scalar_float")
        _emit_dataset(fname, h, lines)
        lines.append("")

    lines.append("")
    lines.append("    return")

    return "\n".join(lines) + "\n"


def _gen_nonsphere_exporter(mapping: dict) -> str:
    """Generate _export_nonsphere_bodies (walls, facets, boxes)."""
    wall_map = mapping.get("_wall", {})

    lines = [
        "def _export_nonsphere_bodies(f):",
        '    """Write /ONDEM/Bodies — walls, facets, boxes."""',
        '    grp = f.require_group("ONDEM/Bodies")',
        "    walls, facets, boxes, others = [], [], [], []",
        "    for b in O.bodies:",
        "        if b is None: continue",
        "        stype = type(b.shape).__name__",
        "        if stype == 'Sphere': continue",
        "        elif stype == 'Wall':      walls.append(b)",
        "        elif stype == 'Facet':     facets.append(b)",
        "        elif stype == 'Box':       boxes.append(b)",
        "        else:                      others.append(b)",
        "",
        "    # --- Walls ---",
        "    if walls:",
        "        wg = grp.require_group('Walls')",
        "        wg.create_dataset('body_id',     data=np.array([b.id for b in walls],            dtype=np.int32))",
        "        wg.create_dataset('material_id', data=np.array([b.material.id for b in walls],   dtype=np.int32))",
        f"        wg.create_dataset('axis',        data=np.array([{wall_map.get('axis','b.shape.axis')} for b in walls], dtype=np.int32))",
        f"        wg.create_dataset('sense',       data=np.array([{wall_map.get('sense','b.shape.sense')} for b in walls], dtype=np.int32))",
        f"        wg.create_dataset('position',    data=np.array([[b.state.pos[0],b.state.pos[1],b.state.pos[2]] for b in walls], dtype=np.float64))",
        "        wg.attrs['shape_type'] = 'wall'",
        "        wg.attrs['count'] = len(walls)",
        "",
        "    # --- Facets ---",
        "    if facets:",
        "        fg = grp.require_group('Facets')",
        "        fg.create_dataset('body_id',     data=np.array([b.id for b in facets], dtype=np.int32))",
        "        fg.create_dataset('material_id', data=np.array([b.material.id for b in facets], dtype=np.int32))",
        "        fg.create_dataset('vertices',    data=np.array([[[v[0],v[1],v[2]] for v in b.shape.vertices] for b in facets], dtype=np.float64))",
        "        fg.create_dataset('normal',      data=np.array([[b.shape.normal[0],b.shape.normal[1],b.shape.normal[2]] for b in facets], dtype=np.float64))",
        "        fg.create_dataset('position',    data=np.array([[b.state.pos[0],b.state.pos[1],b.state.pos[2]] for b in facets], dtype=np.float64))",
        "        fg.attrs['shape_type'] = 'facet'",
        "        fg.attrs['count'] = len(facets)",
        "",
        "    # --- Boxes (ON-DEM schema: box.dimensions) ---",
        "    if boxes:",
        "        bg = grp.require_group('Boxes')",
        "        bg.create_dataset('body_id',     data=np.array([b.id for b in boxes], dtype=np.int32))",
        "        bg.create_dataset('material_id', data=np.array([b.material.id for b in boxes], dtype=np.int32))",
        "        bg.create_dataset('dimensions',  data=np.array([[b.shape.extents[0]*2,b.shape.extents[1]*2,b.shape.extents[2]*2] for b in boxes], dtype=np.float64))",
        "        bg.create_dataset('position',    data=np.array([[b.state.pos[0],b.state.pos[1],b.state.pos[2]] for b in boxes], dtype=np.float64))",
        "        bg.create_dataset('orientation', data=np.array([[b.state.ori[1],b.state.ori[2],b.state.ori[3],b.state.ori[0]] for b in boxes], dtype=np.float64))",
        "        bg.attrs['shape_type'] = 'box'",
        "        bg.attrs['count'] = len(boxes)",
        "",
        "    # --- Other shapes (best effort) ---",
        "    if others:",
        "        og = grp.require_group('Other')",
        "        og.create_dataset('body_id', data=np.array([b.id for b in others], dtype=np.int32))",
        "        _dt = h5py.string_dtype()",
        "        _ds = og.create_dataset('shape_type', (len(others),), dtype=_dt)",
        "        for _ii, b in enumerate(others): _ds[_ii] = type(b.shape).__name__",
        "        og.attrs['note'] = 'shape type not fully supported by ON-DEM schema yet'",
        "",
    ]
    return "\n".join(lines) + "\n"


def _gen_main_function(schema_dir: str, mapping_path: str) -> str:
    return f'''\
# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def export_vtkhdf(filename):
    """Export the current YADE simulation state to an ON-DEM VTKHDF file.

    Generated from schema: {schema_dir}
    Mapping file:          {mapping_path}

    Parameters
    ----------
    filename : str
        Output file path (should end in .vtkhdf or .hdf).
    """
    with h5py.File(filename, "w") as f:

        # 1. VTK PolyData for all bodies (/VTKHDF/)
        n_bodies = _export_bodies(f)

        # 2. Scene metadata
        _export_scene(f)

        # 3. Materials
        _export_materials(f)

        # 4. Non-sphere bodies
        _export_nonsphere_bodies(f)

        # 5. Interactions
        _export_interactions(f)

        # Top-level metadata
        f.attrs["file_format"]         = "ON-DEM VTKHDF"
        f.attrs["file_format_version"] = "0.1-draft"
        f.attrs["source_code"]         = "YADE"
        f.attrs["schema_dir"]          = "{schema_dir}"
        f.attrs["mapping_file"]        = "{mapping_path}"

    n_intrs = sum(1 for i in O.interactions if i.isReal)
    print(f"[export_vtkhdf] Exported {{n_bodies}} bodies, {{n_intrs}} interactions "
          f"at t={{O.time:.6g}} to \\'{{filename}}\\'")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "output.vtkhdf"
    export_vtkhdf(out)
'''


# ---------------------------------------------------------------------------
# Top-level generator
# ---------------------------------------------------------------------------

def generate(schema_dir: str, mapping_path: str, out_path: str):
    print(f"[codegen_yade] Parsing schema from: {schema_dir}")
    schema = parse_schema_dir(schema_dir)

    print(f"[codegen_yade] Loading mapping from: {mapping_path}")
    mapping = _load_mapping(mapping_path)

    print(f"[codegen_yade] Generating exporter...")

    sections = [
        _gen_header(schema_dir, mapping_path),
        _gen_helpers(),
        _gen_scene_exporter(schema, mapping),
        _gen_materials_exporter(schema, mapping),
        _gen_spheres_exporter(schema, mapping),
        _gen_interactions_exporter(schema, mapping),
        _gen_nonsphere_exporter(mapping),
        _gen_main_function(schema_dir, mapping_path),
    ]

    output = "\n".join(sections)

    with open(out_path, "w") as f:
        f.write(output)

    print(f"[codegen_yade] Written to: {out_path}")
    print(f"[codegen_yade] Lines: {output.count(chr(10))}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate YADE→VTKHDF exporter from ON-DEM schema")
    parser.add_argument("schema_dir",
        help="Directory containing ON-DEM schema .py files")
    parser.add_argument("--mapping", default="yade_mapping.json",
        help="Path to YADE field mapping JSON (default: yade_mapping.json)")
    parser.add_argument("--out", default="export_yade_vtkhdf.py",
        help="Output file path (default: export_yade_vtkhdf.py)")

    args = parser.parse_args()
    generate(args.schema_dir, args.mapping, args.out)
