"""
export_yade_vtkhdf.py
ON-DEM WG3 - YADE to VTKHDF exporter

AUTO-GENERATED by codegen_yade.py on 2026-04-07
  Schema dir : schema/
  Mapping    : yade_mapping.json

DO NOT EDIT MANUALLY - re-run the generator to update.

Usage (inside YADE or from yadedaily -x):
    from export_yade_vtkhdf import export_vtkhdf
    export_vtkhdf("output.vtkhdf")

Periodic engine usage:
    O.engines += [PyRunner(
        command='export_vtkhdf("sim_%04d.vtkhdf" % O.iter)',
        iterPeriod=1000)]
"""

import numpy as np
import h5py
import os
import sys


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_gravity():
    """YADE gravity lives on NewtonIntegrator, not on O directly."""
    for eng in O.engines:
        if type(eng).__name__ == "NewtonIntegrator":
            g = eng.gravity
            return [g[0], g[1], g[2]]
    return [0.0, 0.0, 0.0]

def _sphere_volume(b):
    r = b.shape.radius
    return 4.0 / 3.0 * 3.141592653589793 * r**3

def _vec3(v):
    return np.array([v[0], v[1], v[2]], dtype=np.float64)

def _quat(q):
    """YADE: q[0]=w → store as [x,y,z,w]"""
    return np.array([q[1], q[2], q[3], q[0]], dtype=np.float64)

def _mat3_flat(iv):
    """YADE inertia is a Vector3 of principal moments → diagonal 3x3, row-major."""
    return np.array([iv[0],0,0, 0,iv[1],0, 0,0,iv[2]], dtype=np.float64)


def _export_scene(f):
    """Write /ONDEM/Scene — generated from scene schema."""
    grp = f.require_group("ONDEM/Scene")

    #  units: List[str] 
    _dt = h5py.special_dtype(vlen=str)
    _ds = grp.create_dataset("units", (len(['second', 'meter', 'kilogram']),), dtype=_dt)
    for _ii, _v in enumerate(['second', 'meter', 'kilogram']): _ds[_ii] = _v

    #  timestep: float [T]
    grp.attrs["timestep"] = O.dt

    #  time: float [T]
    grp.attrs["time"] = O.time

    #  gravity: Vector3 [L/T²]
    _v = _get_gravity()
    grp.create_dataset("gravity", data=np.array([_v[0],_v[1],_v[2]], dtype=np.float64))


def _export_materials(f):
    """Write /ONDEM/Materials — generated from materials schema."""
    mat_grp = f.require_group("ONDEM/Materials")
    seen_ids = set()
    for b in O.bodies:
        if b is None: continue
        mat = b.material
        if mat.id in seen_ids: continue
        seen_ids.add(mat.id)
        g = mat_grp.create_group(str(mat.id))

        # Extra YADE-specific attributes (not in schema but useful)
        try: g.create_dataset("friction_angle_rad", data=np.float64(float(mat.frictionAngle) if hasattr(mat,'frictionAngle') else 0.0))
        except: pass
        try: g.create_dataset("label", data=np.bytes_(str(mat.label if mat.label else '')))
        except: pass
        try: g.create_dataset("material_type", data=np.bytes_(str(type(mat).__name__)))
        except: pass
        try: g.create_dataset("yade_material_type", data=np.bytes_(str(type(mat).__name__)))
        except: pass

        # --- material_general: These are shared material variables for all materials ---
        # [mandatory] density: float [$M L^{-3}$]
        try:
            g.create_dataset("density", data=np.float64(mat.density))
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] friction_coefficient: float [$-$]
        try:
            g.create_dataset("friction_coefficient", data=np.float64(float(np.tan(mat.frictionAngle)) if hasattr(mat,'frictionAngle') else 0.0))
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] id: int [$-$]
        try:
            g.create_dataset("id", data=np.int32(mat.id))
        except Exception as _e:
            pass  # field not available for this material type

        # --- material_spring_constants: This material describes linear-elastic behaviour with spring constants ---
        # [mandatory] normal_stiffness: float [$F L^{-1}$]
        try:
            g.create_dataset("normal_stiffness", data=np.float64(mat.kn))
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] shear_stiffness: float [$F L^{-1}$]
        try:
            g.create_dataset("shear_stiffness", data=np.float64(mat.ks))
        except Exception as _e:
            pass  # field not available for this material type

        # --- material_elastic_constants: This material describes linear-elastic behaviour with elasticity parameters ---
        # [mandatory] young: float [$F L^{-2}$]
        try:
            g.create_dataset("young", data=np.float64(mat.young))
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] poisson: float [$-$]
        try:
            g.create_dataset("poisson", data=np.float64(mat.poisson))
        except Exception as _e:
            pass  # field not available for this material type

        # --- material_visco_elastic_constants_COR: This material describes visco-elastic behaviour with constant coefficient of restitution ---
        # [mandatory] damping_coefficient_normal: float [$M T^{-1}$]
        try:
            g.create_dataset("damping_coefficient_normal", data=np.float64(mat.cn))
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] damping_coefficient_shear: float [$M T^{-1}$]
        try:
            g.create_dataset("damping_coefficient_shear", data=np.float64(mat.cs))
        except Exception as _e:
            pass  # field not available for this material type

        # --- material_visco_elastic_variable_COR: This material describes visco-elastic behaviour with variable coefficient of restitution ---
        # [mandatory] dissipative_constant: float [$ $]
        try:
            g.create_dataset("dissipative_constant", data=np.float64(mat.alpha))
        except Exception as _e:
            pass  # field not available for this material type


def _export_spheres(f):
    """Write sphere particles to /VTKHDF/ PointData — generated from schema."""

    # --- Collect sphere data ---
    _material_id_list = []
    _clump_id_list = []
    _body_id_list = []
    _position_list = []
    _velocity_list = []
    _orientation_list = []
    _angular_velocity_list = []
    _mass_list = []
    _inertia_list = []
    _volume_list = []
    _radius_list = []

    for b in O.bodies:
        if b is None: continue
        if type(b.shape).__name__ != 'Sphere': continue

        try: _material_id_list.append(b.material.id)
        except: _material_id_list.append(None)
        try: _clump_id_list.append(b.clumpId)
        except: _clump_id_list.append(None)
        try: _body_id_list.append(b.id)
        except: _body_id_list.append(None)
        # UNMAPPED: body_state
        # UNMAPPED: body_shape
        try: _position_list.append(b.state.pos)
        except: _position_list.append(None)
        try: _velocity_list.append(b.state.vel)
        except: _velocity_list.append(None)
        try: _orientation_list.append(b.state.ori)
        except: _orientation_list.append(None)
        try: _angular_velocity_list.append(b.state.angVel)
        except: _angular_velocity_list.append(None)
        try: _mass_list.append(b.state.mass)
        except: _mass_list.append(None)
        try: _inertia_list.append(b.state.inertia)
        except: _inertia_list.append(None)
        try: _volume_list.append(_sphere_volume(b))
        except: _volume_list.append(None)
        # UNMAPPED: color
        try: _radius_list.append(b.shape.radius)
        except: _radius_list.append(None)

    N = len(_body_id_list)
    if N == 0:
        print("[export_vtkhdf] Warning: no sphere bodies found")
        return 0

    # --- Write /VTKHDF/ VTK PolyData structure ---
    vtk = f.require_group("VTKHDF")
    vtk.attrs.create("Type",    data=np.bytes_("PolyData"))
    vtk.attrs.create("Version", data=np.array([2, 0], dtype=np.int64))

    # Points = sphere centres
    pos_arr = np.array([[p[0],p[1],p[2]] for p in _position_list], dtype=np.float64)
    vtk.create_dataset("Points", data=pos_arr)
    vtk.create_dataset("NumberOfPoints", data=np.array([N], dtype=np.int64))

    # Empty cell structures (required by VTK HDF spec for PolyData)
    for _sec in ["Verts","Lines","Polygons","Strips"]:
        _sg = vtk.require_group(_sec)
        _sg.create_dataset("NumberOfCells",           data=np.array([0], dtype=np.int64))
        _sg.create_dataset("NumberOfConnectivityIds", data=np.array([0], dtype=np.int64))
        _sg.create_dataset("Offsets",                 data=np.array([0], dtype=np.int64))
        _sg.create_dataset("Connectivity",            data=np.array([], dtype=np.int64))

    pd = vtk.require_group("PointData")

    # --- Write per-particle datasets ---
    # [mandatory] material_id: int [$-$]
    pd.create_dataset("material_id", data=np.array(_material_id_list, dtype=np.int32))

    # [mandatory] clump_id: int [$-$]
    pd.create_dataset("clump_id", data=np.array(_clump_id_list, dtype=np.int32))

    # [mandatory] body_id: int [$-$]
    pd.create_dataset("body_id", data=np.array(_body_id_list, dtype=np.int32))

    # [mandatory] position: Vector3 [$L$]
    pd.create_dataset("position", data=np.array([[v[0],v[1],v[2]] for v in _position_list], dtype=np.float64))

    # [mandatory] velocity: Vector3 [$L T^{-1}$]
    pd.create_dataset("velocity", data=np.array([[v[0],v[1],v[2]] for v in _velocity_list], dtype=np.float64))

    # [mandatory] orientation: Quaternion [$-$]
    pd.create_dataset("orientation", data=np.array([[q[1],q[2],q[3],q[0]] for q in _orientation_list], dtype=np.float64))

    # [mandatory] angular_velocity: Vector3 [$T^{-1}$]
    pd.create_dataset("angular_velocity", data=np.array([[v[0],v[1],v[2]] for v in _angular_velocity_list], dtype=np.float64))

    # [mandatory] mass: float [$M$]
    pd.create_dataset("mass", data=np.array(_mass_list, dtype=np.float64))

    # [mandatory] inertia: Matrix3 [$M L^{2}$]
    pd.create_dataset("inertia", data=np.array([_mat3_flat(iv) for iv in _inertia_list], dtype=np.float64))

    # [mandatory] volume: float [$L^{3}$]
    pd.create_dataset("volume", data=np.array(_volume_list, dtype=np.float64))

    # [mandatory] radius: float 
    pd.create_dataset("radius", data=np.array(_radius_list, dtype=np.float64))

    return N


def _export_interactions(f):
    """Write /ONDEM/Interactions — generated from interaction schema."""
    ig = f.require_group("ONDEM/Interactions")

    intrs = [i for i in O.interactions if i.isReal]
    ig.attrs['count'] = len(intrs)
    if not intrs: return

    # --- Accumulate per-interaction data ---
    _id1_list = []
    _id2_list = []
    _virtual_list = []
    _lifespan_list = []
    _normal_list = []
    _normal_force_list = []
    _shear_force_list = []
    _ks_list = []
    _hertz_young_list = []
    _hertz_poisson_list = []
    _contact_point_list = []
    _overlap_list = []
    _reference_radius_1_list = []
    _reference_radius_2_list = []
    _geom_type_list = []
    _phys_type_list = []
    _normal_stiffness_list = []
    _shear_stiffness_list = []
    _friction_coefficient_interaction_list = []
    _normal_damping_ratio_list = []
    _shear_damping_ratio_list = []
    _isSliding_list = []
    _shear_force_elastic_list = []
    _shear_force_viscous_list = []
    _normal_force_viscous_list = []

    for i in intrs:

        try: _id1_list.append(i.id1)
        except: _id1_list.append(None)
        try: _id2_list.append(i.id2)
        except: _id2_list.append(None)
        try: _virtual_list.append(not i.isReal)
        except: _virtual_list.append(None)
        try: _lifespan_list.append(i.phys.lifespan if hasattr(i.phys,'lifespan') else 0.0)
        except: _lifespan_list.append(None)
        try: _normal_list.append(i.geom.normal)
        except: _normal_list.append(None)
        try: _normal_force_list.append(i.phys.normalForce.norm())
        except: _normal_force_list.append(None)
        try: _shear_force_list.append(i.phys.shearForce)
        except: _shear_force_list.append(None)
        try: _ks_list.append(i.phys.ks)
        except: _ks_list.append(None)
        try: _hertz_young_list.append(i.phys.kno)
        except: _hertz_young_list.append(None)
        try: _hertz_poisson_list.append(i.phys.kso)
        except: _hertz_poisson_list.append(None)
        try: _contact_point_list.append(i.geom.contactPoint)
        except: _contact_point_list.append(None)
        try: _overlap_list.append(i.geom.penetrationDepth)
        except: _overlap_list.append(None)
        try: _reference_radius_1_list.append(i.geom.refR1)
        except: _reference_radius_1_list.append(None)
        try: _reference_radius_2_list.append(i.geom.refR2)
        except: _reference_radius_2_list.append(None)
        try: _geom_type_list.append(type(i.geom).__name__)
        except: _geom_type_list.append(None)
        try: _phys_type_list.append(type(i.phys).__name__)
        except: _phys_type_list.append(None)
        try: _normal_stiffness_list.append(i.phys.kn  if hasattr(i.phys,'kn')  else 0.0)
        except: _normal_stiffness_list.append(None)
        try: _shear_stiffness_list.append(i.phys.ks  if hasattr(i.phys,'ks')  else 0.0)
        except: _shear_stiffness_list.append(None)
        try: _friction_coefficient_interaction_list.append(i.phys.tangensOfFrictionAngle if hasattr(i.phys,'tangensOfFrictionAngle') else 0.0)
        except: _friction_coefficient_interaction_list.append(None)
        try: _normal_damping_ratio_list.append(i.phys.betan if hasattr(i.phys,'betan') else float('nan'))
        except: _normal_damping_ratio_list.append(None)
        try: _shear_damping_ratio_list.append(i.phys.betas if hasattr(i.phys,'betas') else float('nan'))
        except: _shear_damping_ratio_list.append(None)
        try: _isSliding_list.append(int(i.phys.isSliding) if hasattr(i.phys,'isSliding') else 0)
        except: _isSliding_list.append(None)
        try: _shear_force_elastic_list.append(i.phys.shearElastic if hasattr(i.phys,'shearElastic') else None)
        except: _shear_force_elastic_list.append(None)
        try: _shear_force_viscous_list.append(i.phys.shearViscous  if hasattr(i.phys,'shearViscous')  else None)
        except: _shear_force_viscous_list.append(None)
        try: _normal_force_viscous_list.append(i.phys.normalViscous.norm() if hasattr(i.phys,'normalViscous') else float('nan'))
        except: _normal_force_viscous_list.append(None)

    # --- Write datasets ---
    # id1: int 
    ig.create_dataset("id1", data=np.array(_id1_list, dtype=np.int32))

    # id2: int 
    ig.create_dataset("id2", data=np.array(_id2_list, dtype=np.int32))

    # virtual: bool 
    ig.create_dataset("virtual", data=np.array(_virtual_list, dtype=np.int8))

    # lifespan: float 
    ig.create_dataset("lifespan", data=np.array(_lifespan_list, dtype=np.float64))

    # normal: Vector3 
    ig.create_dataset("normal", data=np.array([[v[0],v[1],v[2]] if v is not None else [0,0,0] for v in _normal_list], dtype=np.float64))

    # normal_force: float [F]
    ig.create_dataset("normal_force", data=np.array(_normal_force_list, dtype=np.float64))

    # shear_force: Vector3 [F]
    ig.create_dataset("shear_force", data=np.array([[v[0],v[1],v[2]] if v is not None else [0,0,0] for v in _shear_force_list], dtype=np.float64))

    # ks: float [F/L]
    ig.create_dataset("ks", data=np.array(_ks_list, dtype=np.float64))

    # hertz_young: float [F/L²]
    ig.create_dataset("hertz_young", data=np.array(_hertz_young_list, dtype=np.float64))

    # hertz_poisson: float 
    ig.create_dataset("hertz_poisson", data=np.array(_hertz_poisson_list, dtype=np.float64))

    ig.create_dataset("contact_point", data=np.array([[v[0],v[1],v[2]] if v is not None else [0,0,0] for v in _contact_point_list], dtype=np.float64))

    ig.create_dataset("overlap", data=np.array(_overlap_list, dtype=np.float64))

    ig.create_dataset("reference_radius_1", data=np.array(_reference_radius_1_list, dtype=np.float64))

    ig.create_dataset("reference_radius_2", data=np.array(_reference_radius_2_list, dtype=np.float64))

    _dt = h5py.special_dtype(vlen=str)
    _ds = ig.create_dataset("geom_type", (len(intrs),), dtype=_dt)
    for _ii, _v in enumerate(_geom_type_list): _ds[_ii] = str(_v) if _v else ""

    _dt = h5py.special_dtype(vlen=str)
    _ds = ig.create_dataset("phys_type", (len(intrs),), dtype=_dt)
    for _ii, _v in enumerate(_phys_type_list): _ds[_ii] = str(_v) if _v else ""

    ig.create_dataset("normal_stiffness", data=np.array(_normal_stiffness_list, dtype=np.float64))

    ig.create_dataset("shear_stiffness", data=np.array(_shear_stiffness_list, dtype=np.float64))

    ig.create_dataset("friction_coefficient_interaction", data=np.array(_friction_coefficient_interaction_list, dtype=np.float64))

    ig.create_dataset("normal_damping_ratio", data=np.array(_normal_damping_ratio_list, dtype=np.float64))

    ig.create_dataset("shear_damping_ratio", data=np.array(_shear_damping_ratio_list, dtype=np.float64))

    ig.create_dataset("isSliding", data=np.array(_isSliding_list, dtype=np.int32))

    ig.create_dataset("shear_force_elastic", data=np.array([[v[0],v[1],v[2]] if v is not None else [0,0,0] for v in _shear_force_elastic_list], dtype=np.float64))

    ig.create_dataset("shear_force_viscous", data=np.array([[v[0],v[1],v[2]] if v is not None else [0,0,0] for v in _shear_force_viscous_list], dtype=np.float64))

    ig.create_dataset("normal_force_viscous", data=np.array(_normal_force_viscous_list, dtype=np.float64))


def _export_nonsphere_bodies(f):
    """Write /ONDEM/Bodies — walls, facets, boxes."""
    grp = f.require_group("ONDEM/Bodies")
    walls, facets, boxes, others = [], [], [], []
    for b in O.bodies:
        if b is None: continue
        stype = type(b.shape).__name__
        if stype == 'Sphere': continue
        elif stype == 'Wall':      walls.append(b)
        elif stype == 'Facet':     facets.append(b)
        elif stype == 'Box':       boxes.append(b)
        else:                      others.append(b)

    # --- Walls ---
    if walls:
        wg = grp.require_group('Walls')
        wg.create_dataset('body_id',     data=np.array([b.id for b in walls],            dtype=np.int32))
        wg.create_dataset('material_id', data=np.array([b.material.id for b in walls],   dtype=np.int32))
        wg.create_dataset('axis',        data=np.array([b.shape.axis for b in walls], dtype=np.int32))
        wg.create_dataset('sense',       data=np.array([b.shape.sense for b in walls], dtype=np.int32))
        wg.create_dataset('position',    data=np.array([[b.state.pos[0],b.state.pos[1],b.state.pos[2]] for b in walls], dtype=np.float64))
        wg.attrs['shape_type'] = 'wall'
        wg.attrs['count'] = len(walls)

    # --- Facets ---
    if facets:
        fg = grp.require_group('Facets')
        fg.create_dataset('body_id',     data=np.array([b.id for b in facets], dtype=np.int32))
        fg.create_dataset('material_id', data=np.array([b.material.id for b in facets], dtype=np.int32))
        fg.create_dataset('vertices',    data=np.array([[[v[0],v[1],v[2]] for v in b.shape.vertices] for b in facets], dtype=np.float64))
        fg.create_dataset('normal',      data=np.array([[b.shape.normal[0],b.shape.normal[1],b.shape.normal[2]] for b in facets], dtype=np.float64))
        fg.create_dataset('position',    data=np.array([[b.state.pos[0],b.state.pos[1],b.state.pos[2]] for b in facets], dtype=np.float64))
        fg.attrs['shape_type'] = 'facet'
        fg.attrs['count'] = len(facets)

    # --- Boxes (ON-DEM schema: box.dimensions) ---
    if boxes:
        bg = grp.require_group('Boxes')
        bg.create_dataset('body_id',     data=np.array([b.id for b in boxes], dtype=np.int32))
        bg.create_dataset('material_id', data=np.array([b.material.id for b in boxes], dtype=np.int32))
        bg.create_dataset('dimensions',  data=np.array([[b.shape.extents[0]*2,b.shape.extents[1]*2,b.shape.extents[2]*2] for b in boxes], dtype=np.float64))
        bg.create_dataset('position',    data=np.array([[b.state.pos[0],b.state.pos[1],b.state.pos[2]] for b in boxes], dtype=np.float64))
        bg.create_dataset('orientation', data=np.array([[b.state.ori[1],b.state.ori[2],b.state.ori[3],b.state.ori[0]] for b in boxes], dtype=np.float64))
        bg.attrs['shape_type'] = 'box'
        bg.attrs['count'] = len(boxes)

    # --- Other shapes (best effort) ---
    if others:
        og = grp.require_group('Other')
        og.create_dataset('body_id', data=np.array([b.id for b in others], dtype=np.int32))
        _dt = h5py.special_dtype(vlen=str)
        _ds = og.create_dataset('shape_type', (len(others),), dtype=_dt)
        for _ii, b in enumerate(others): _ds[_ii] = type(b.shape).__name__
        og.attrs['note'] = 'shape type not fully supported by ON-DEM schema yet'


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def export_vtkhdf(filename):
    """Export the current YADE simulation state to an ON-DEM VTKHDF file.

    Generated from schema: schema/
    Mapping file:          yade_mapping.json

    Parameters
    ----------
    filename : str
        Output file path (should end in .vtkhdf or .hdf).
    """
    with h5py.File(filename, "w") as f:

        # 1. VTK PolyData for spheres (/VTKHDF/)
        n_spheres = _export_spheres(f)

        # 2. Scene metadata
        _export_scene(f)

        # 3. Materials
        _export_materials(f)

        # 4. Non-sphere bodies
        _export_nonsphere_bodies(f)

        # 5. Interactions
        _export_interactions(f)

        # Top-level metadata
        f.attrs["file_format"]         = "ON-DEM VTKHDF"
        f.attrs["file_format_version"] = "0.1-draft"
        f.attrs["source_code"]         = "YADE"
        f.attrs["schema_dir"]          = "schema/"
        f.attrs["mapping_file"]        = "yade_mapping.json"

    n_intrs = sum(1 for i in O.interactions if i.isReal)
    print(f"[export_vtkhdf] Exported {n_spheres} spheres, {n_intrs} interactions "
          f"at t={O.time:.6g} to \'{filename}\'")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "output.vtkhdf"
    export_vtkhdf(out)
