"""
export_yade_vtkhdf.py
ON-DEM WG3 - YADE to VTKHDF exporter

AUTO-GENERATED by codegen_yade.py on 2026-10-02
  Schema dir : ../..
  Mapping    : yade_mapping.json

DO NOT EDIT MANUALLY - re-run the generator to update.

Usage (inside YADE or from yadedaily -x):
    from export_yade_vtkhdf import export_vtkhdf
    export_vtkhdf("output.vtkhdf")                      # one display group 'all'

    # two display groups, i.e. two blocks in ParaView
    export_vtkhdf("output.vtkhdf",
                  display_group_names=["particles", "geometry"],
                  display_group=lambda b: 0 if isinstance(b.shape, Sphere) else 1)

Periodic engine usage (one timestep per file):
    O.engines += [PyRunner(
        command='export_vtkhdf("sim_%04d.vtkhdf" % O.iter)',
        iterPeriod=1000)]
"""

import numpy as np
import h5py
import os
import sys

from hdf5_utils import (hdf5_write_field, hdf5_write_column, hdf5_write_string_array,
                        point_array, column_array, snake_case, validate_display_groups,
                        vtkhdf_init_multiblock, vtkhdf_write_polydata_block, QUATERNION_ORDER)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_gravity():
    """YADE gravity lives on NewtonIntegrator, not on O directly."""
    for eng in O.engines:
        if type(eng).__name__ == "NewtonIntegrator":
            g = eng.gravity
            return [g[0], g[1], g[2]]
    return [0.0, 0.0, 0.0]

def _sphere_volume(b):
    r = b.shape.radius
    return 4.0 / 3.0 * 3.141592653589793 * r**3

def _vec3(v):
    return np.array([v[0], v[1], v[2]], dtype=np.float64)

def _diag3(iv):
    """YADE inertia is a Vector3 of principal moments → diagonal 3x3."""
    return [[iv[0], 0.0, 0.0], [0.0, iv[1], 0.0], [0.0, 0.0, iv[2]]]


# ---------------------------------------------------------------------------
# Display groups (set by export_vtkhdf arguments)
# ---------------------------------------------------------------------------

_DISPLAY_GROUP_NAMES = ["all"]
_DISPLAY_GROUP_SOURCE = None

def _display_group_names():
    """scene.display_group_names for the current export."""
    return list(_DISPLAY_GROUP_NAMES)

def _display_group(b):
    """base_body.display_group of body b: from the dict {body_id: index} or the
    callable given to export_vtkhdf; 0 (the default group) otherwise."""
    src = _DISPLAY_GROUP_SOURCE
    if src is None:
        return 0
    if callable(src):
        return src(b)
    return src.get(b.id, 0)

def _collect(items, fields):
    """Evaluate every getter of fields on every item; a failing getter gives None."""
    cols = {}
    for name, _h, _mandatory, get in fields:
        vals = []
        for it in items:
            try: vals.append(get(it))
            except Exception: vals.append(None)
        cols[name] = vals
    return cols


def _export_scene(f):
    """Write /ONDEM/Scene — generated from scene schema."""
    grp = f.require_group("ONDEM/Scene")

    #  units: List[str] 
    hdf5_write_field(grp, "units", "string_list", ['second', 'meter', 'kilogram'], scalar_as_dataset=False)

    #  timestep: float [T]
    hdf5_write_field(grp, "timestep", "scalar_float", O.dt, scalar_as_dataset=False)

    #  time: float [T]
    hdf5_write_field(grp, "time", "scalar_float", O.time, scalar_as_dataset=False)

    #  gravity: Vector3 [L/T²]
    hdf5_write_field(grp, "gravity", "vector3", _get_gravity(), scalar_as_dataset=False)

    # [optional] display_group_names: List[str] [$-$]
    hdf5_write_field(grp, "display_group_names", "string_list", _display_group_names(), scalar_as_dataset=False)


def _export_materials(f):
    """Write /ONDEM/Materials — generated from materials schema."""
    mat_grp = f.require_group("ONDEM/Materials")
    seen_ids = set()
    for b in O.bodies:
        if b is None: continue
        mat = b.material
        if mat.id in seen_ids: continue
        seen_ids.add(mat.id)
        g = mat_grp.create_group(str(mat.id))

        # Extra YADE-specific attributes (not in schema but useful)
        try: g.create_dataset("friction_angle_rad", data=np.float64(float(mat.frictionAngle) if hasattr(mat,'frictionAngle') else 0.0))
        except: pass
        try: g.create_dataset("label", data=str(mat.label if mat.label else '').encode("utf-8"))
        except: pass
        try: g.create_dataset("material_type", data=str(type(mat).__name__).encode("utf-8"))
        except: pass

        # --- base_material: General properties shared by all materials. ---
        # [mandatory] id: int [$-$]
        try:
            hdf5_write_field(g, "id", "scalar_int", mat.id, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] density: float [$ML^{-3}$]
        try:
            hdf5_write_field(g, "density", "scalar_float", mat.density, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type


# Per-body fields: (name, hdf5 type, mandatory, getter).
# Generated from the schema; getters are the mapping expressions.
_BODY_FIELDS = [
    # [mandatory] base_body.material_id: int [$-$]
    ("material_id", "scalar_int", True, lambda b: b.material.id),
    # [mandatory] base_body.clump_id: int [$-$]
    ("clump_id", "scalar_int", True, lambda b: b.clumpId),
    # [mandatory] base_body.body_id: int [$-$]
    ("body_id", "scalar_int", True, lambda b: b.id),
    # SKIPPED base_body.body_state: nested type type(base_state)
    # SKIPPED base_body.body_shape: nested type type(base_shape)
    # [mandatory] base_state.position: Vector3 [$L$]
    ("position", "vector3", True, lambda b: b.state.pos),
    # [mandatory] base_state.velocity: Vector3 [$L T^{-1}$]
    ("velocity", "vector3", True, lambda b: b.state.vel),
    # [mandatory] base_state.orientation: Quaternion [$-$]
    ("orientation", "quaternion", True, lambda b: [b.state.ori[3], b.state.ori[0], b.state.ori[1], b.state.ori[2]]),
    # [mandatory] base_state.angular_velocity: Vector3 [$T^{-1}$]
    ("angular_velocity", "vector3", True, lambda b: b.state.angVel),
    # [mandatory] base_state.mass: float [$M$]
    ("mass", "scalar_float", True, lambda b: b.state.mass),
    # [mandatory] base_state.inertia: Matrix3 [$M L^{2}$]
    ("inertia", "matrix3", True, lambda b: _diag3(b.state.inertia)),
    # [mandatory] base_state.volume: float [$L^{3}$]
    ("volume", "scalar_float", True, lambda b: _sphere_volume(b)),
    # [optional] thermal.temperature: float [$\Theta$]
    ("temperature", "scalar_float", False, lambda b: b.state.T),
    # [optional] liquid_film.liquid_film_volume: float [L^3]
    ("liquid_film_volume", "scalar_float", False, lambda b: b.state.liquidFilmVolume),
    # [mandatory] sphere.radius: float
    ("radius", "scalar_float", True, lambda b: b.shape.radius),
]

# Shape fields per /ONDEM/Bodies group (fields that are not in the blocks)
_SHAPE_FIELDS = {
  "sphere": [
    # radius: in the VTKHDF blocks
  ],
  "box": [
      # [mandatory] box.dimensions: Vector3
      ("dimensions", "vector3", True, lambda b: [b.shape.extents[0]*2, b.shape.extents[1]*2, b.shape.extents[2]*2]),
  ],
  "polyhedron": [
    # SKIPPED polyhedron.vertices: type list cannot be written per body yet
  ],
  # wall: not in the schema yet (non-normative)
  "wall": [
      ("axis", "scalar_int", True, lambda b: b.shape.axis),
      ("sense", "scalar_int", True, lambda b: b.shape.sense),
  ],
  # facet: not in the schema yet (non-normative)
  "facet": [
      ("vertices", "matrix3", True, lambda b: [[v[0],v[1],v[2]] for v in b.shape.vertices]),
      ("normal", "vector3", True, lambda b: b.shape.normal),
  ],
}

_BLOCK_FIELDS = ['radius', 'velocity', 'angular_velocity', 'orientation']
_NOT_IN_ONDEM = ['angular_velocity', 'display_group', 'orientation', 'position', 'radius', 'velocity']
_SHAPE_GROUPS = {'Sphere': 'sphere', 'Box': 'box', 'Polyhedra': 'polyhedron', 'Wall': 'wall', 'Facet': 'facet'}

def _shape_group(b):
    """/ONDEM/Bodies group of body b; "other" for shapes not handled yet."""
    try: return _SHAPE_GROUPS.get(type(b.shape).__name__, "other")
    except Exception: return "other"

def _shape_type(b):
    try: return str(type(b.shape).__name__)
    except Exception: return ""

def _export_bodies(f):
    """Write the bodies: one PolyData block per display group in /VTKHDF,
    the per-body fields that are not in the blocks in /ONDEM/Bodies/<shape group>/."""
    bodies = [b for b in O.bodies if b is not None]
    names = _display_group_names()
    cols = _collect(bodies, _BODY_FIELDS)
    body_ids = cols["body_id"]
    if None in body_ids or len(set(body_ids)) != len(body_ids):
        raise ValueError("[export_vtkhdf] body ids must be unique and defined")
    groups = [_display_group(b) for b in bodies]
    validate_display_groups(names, dict(zip(body_ids, groups)))
    types = {name: h for name, h, _m, _g in _BODY_FIELDS}

    # 1. /VTKHDF: one PolyData block per display group, empty groups included
    vtkhdf_init_multiblock(f)
    for gi, name in enumerate(names):
        idx = [k for k, g in enumerate(groups) if g == gi]
        sel = lambda col: [col[k] for k in idx]
        block_fields = [n for n in _BLOCK_FIELDS if n in cols]
        vtkhdf_write_polydata_block(
            f, name, sel(body_ids),
            points=point_array(sel(cols["position"]), 3),
            point_data={n: column_array(sel(cols[n]), types[n]) for n in block_fields},
            point_data_attrs={n: {"order": QUATERNION_ORDER} for n in block_fields if types[n] == "quaternion"},
        )

    # 2. /ONDEM/Bodies/<shape group>: body_id (join key) + fields not in the blocks
    bodies_grp = f.require_group("ONDEM/Bodies")
    shape_groups = [_shape_group(b) for b in bodies]
    for sg in sorted(set(shape_groups)):
        idx = [k for k, s in enumerate(shape_groups) if s == sg]
        sel = lambda col: [col[k] for k in idx]
        members = sel(bodies)
        shape_fields = _SHAPE_FIELDS.get(sg, [])
        shape_cols = _collect(members, shape_fields)
        g = bodies_grp.create_group(sg)
        g.attrs["count"] = len(idx)
        hdf5_write_column(g, "body_id", sel(body_ids), "scalar_int")
        for name, h, mandatory, _get in _BODY_FIELDS + shape_fields:
            if name in _NOT_IN_ONDEM or name == "body_id":
                continue
            vals = sel(cols[name]) if name in cols else shape_cols[name]
            if not mandatory and all(v is None for v in vals):
                continue
            hdf5_write_column(g, name, vals, h)
        if sg == "other":
            hdf5_write_string_array(g, "shape_type", [_shape_type(b) for b in members])
            g.attrs["note"] = "shape type not supported by the ON-DEM schema yet"

    return len(bodies)


# Per-interaction fields: (name, hdf5 type, mandatory, getter).
_INTERACTION_FIELDS = [
    # UNMAPPED base_interaction.model
    # [mandatory] base_interaction.id1: int
    ("id1", "scalar_int", True, lambda i: i.id1),
    # [mandatory] base_interaction.id2: int
    ("id2", "scalar_int", True, lambda i: i.id2),
    # [optional] base_interaction.virtual: bool
    ("virtual", "scalar_bool", False, lambda i: not i.isReal),
    # UNMAPPED base_interaction.creation_time
    # [mandatory] normal.normal: Vector3 [$-$]
    ("normal", "vector3", True, lambda i: i.geom.normal),
    # [mandatory] normal.normal_force: float [$F$]
    ("normal_force", "scalar_float", True, lambda i: (i.phys.normalForce.norm() * (1.0 if i.phys.normalForce.dot(i.geom.normal) >= 0 else -1.0))),
    #  shear.shear_force: Vector3 [$F$]
    ("shear_force", "vector3", False, lambda i: i.phys.shearForce),
    # [mandatory] shear_linear.ks: float [$F/L$]
    ("ks", "scalar_float", True, lambda i: i.phys.ks),
    # [mandatory] normal_linear.kn: float [$F/L$]
    ("kn", "scalar_float", True, lambda i: i.phys.kn),
    # [mandatory] normal_hertz.hertz_young: float [$F/L²$]
    ("hertz_young", "scalar_float", True, lambda i: i.phys.young if hasattr(i.phys,'young') else float('nan')),
    # [mandatory] normal_hertz.hertz_poisson: float [$-$]
    ("hertz_poisson", "scalar_float", True, lambda i: i.phys.poisson if hasattr(i.phys,'poisson') else float('nan')),
    # not in the schema (mapping _interaction_geometry)
    ("contact_point", "vector3", False, lambda i: i.geom.contactPoint),
    ("overlap", "scalar_float", False, lambda i: i.geom.penetrationDepth),
    ("reference_radius_1", "scalar_float", False, lambda i: i.geom.refR1),
    ("reference_radius_2", "scalar_float", False, lambda i: i.geom.refR2),
    # not in the schema (mapping _extra_interaction_attributes)
    ("geom_type", "string", False, lambda i: type(i.geom).__name__),
    ("phys_type", "string", False, lambda i: type(i.phys).__name__),
    ("normal_stiffness", "scalar_float", False, lambda i: i.phys.kn if hasattr(i.phys,'kn') else float('nan')),
    ("shear_stiffness", "scalar_float", False, lambda i: i.phys.ks if hasattr(i.phys,'ks') else float('nan')),
    ("friction_coefficient_interaction", "scalar_float", False, lambda i: i.phys.tangensOfFrictionAngle if hasattr(i.phys,'tangensOfFrictionAngle') else float('nan')),
]

def _interaction_type(i):
    try: return snake_case(str(type(i.phys).__name__))
    except Exception: return "unknown"

def _export_interactions(f):
    """Write /ONDEM/Interactions/<type>/: one group per interaction type (snake_case)."""
    ig_root = f.require_group("ONDEM/Interactions")
    intrs = [i for i in O.interactions if i.isReal]
    by_type = {}
    for i in intrs:
        by_type.setdefault(_interaction_type(i), []).append(i)

    for itype in sorted(by_type):
        members = by_type[itype]
        ig = ig_root.create_group(itype)
        ig.attrs["count"] = len(members)
        cols = _collect(members, _INTERACTION_FIELDS)
        for name, h, mandatory, _get in _INTERACTION_FIELDS:
            vals = cols[name]
            if not mandatory and all(v is None for v in vals):
                continue
            hdf5_write_column(ig, name, vals, h)

    return len(intrs)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def export_vtkhdf(filename, display_group_names=None, display_group=None):
    """Export the current simulation state to an ON-DEM VTKHDF file (one timestep).

    Generated from schema: ../..
    Mapping file:          yade_mapping.json

    Parameters
    ----------
    filename : str
        Output file path (should end in .vtkhdf or .hdf).
    display_group_names : list of str, optional
        scene.display_group_names: one VTKHDF block per name, in this order.
        Default ['all'].
    display_group : dict or callable, optional
        base_body.display_group of each body, an index into display_group_names:
        a dict {body_id: index} (bodies not in the dict get 0) or a callable
        body -> index. Default: every body in group 0.

    Raises ValueError (and writes no file) if a name or an index is invalid.
    """
    global _DISPLAY_GROUP_NAMES, _DISPLAY_GROUP_SOURCE
    _DISPLAY_GROUP_NAMES = list(display_group_names) if display_group_names is not None else ["all"]
    _DISPLAY_GROUP_SOURCE = display_group

    try:
        with h5py.File(filename, "w") as f:

            # 1. Bodies: /VTKHDF blocks (one per display group) + /ONDEM/Bodies
            n_bodies = _export_bodies(f)

            # 2. Scene metadata (includes display_group_names)
            _export_scene(f)

            # 3. Materials
            _export_materials(f)

            # 4. Interactions
            n_intrs = _export_interactions(f)

            # Top-level metadata
            f.attrs["file_format"]         = "ON-DEM VTKHDF"
            f.attrs["file_format_version"] = "0.2-draft"
            f.attrs["schema_dir"]          = "../.."
            f.attrs["mapping_file"]        = "yade_mapping.json"
    except Exception:
        # do not leave a half-written file behind
        if os.path.exists(filename):
            os.remove(filename)
        raise

    print(f"[export_vtkhdf] Exported {n_bodies} bodies in {len(_DISPLAY_GROUP_NAMES)} display group(s), "
          f"{n_intrs} interactions at t={O.time:.6g} to '{filename}'")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "output.vtkhdf"
    export_vtkhdf(out)
