"""
export_yade_vtkhdf.py
ON-DEM WG3 - YADE to VTKHDF exporter

AUTO-GENERATED by codegen_yade.py on 2026-10-03
  Schema dir : ../..
  Mapping    : yade_mapping.json

DO NOT EDIT MANUALLY - re-run the generator to update.

Usage (inside YADE or from yadedaily -x):
    from export_yade_vtkhdf import export_vtkhdf
    export_vtkhdf("output.vtkhdf")      # default groups: spheres -> 'Points', other shapes -> 'Others'

    # user-defined display groups (names are required when display_group is given)
    export_vtkhdf("output.vtkhdf",
                  display_group_names=["particles", "geometry"],
                  display_group=lambda b: 0 if isinstance(b.shape, Sphere) else 1)

Periodic engine usage (one timestep per file):
    O.engines += [PyRunner(
        command='export_vtkhdf("sim_%04d.vtkhdf" % O.iter)',
        iterPeriod=1000)]
"""

import numpy as np
import h5py
import os
import sys

from hdf5_utils import (hdf5_write_field, hdf5_write_column, hdf5_write_string_array,
                        point_array, column_array, snake_case, validate_display_groups,
                        vtkhdf_init_multiblock, vtkhdf_write_polydata_block, QUATERNION_ORDER)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_gravity():
    """YADE gravity lives on NewtonIntegrator, not on O directly."""
    for eng in O.engines:
        if type(eng).__name__ == "NewtonIntegrator":
            g = eng.gravity
            return [g[0], g[1], g[2]]
    return [0.0, 0.0, 0.0]

def _sphere_volume(b):
    r = b.shape.radius
    return 4.0 / 3.0 * 3.141592653589793 * r**3

def _vec3(v):
    return np.array([v[0], v[1], v[2]], dtype=np.float64)

def _diag3(iv):
    """YADE inertia is a Vector3 of principal moments → diagonal 3x3."""
    return [[iv[0], 0.0, 0.0], [0.0, iv[1], 0.0], [0.0, 0.0, iv[2]]]


# ---------------------------------------------------------------------------
# Display groups (set by export_vtkhdf arguments)
# ---------------------------------------------------------------------------

# default display groups (decision 18): spheres -> Points, every other shape -> Others
_DEFAULT_DISPLAY_GROUP_NAMES = ["Points", "Others"]
_DISPLAY_GROUP_NAMES = list(_DEFAULT_DISPLAY_GROUP_NAMES)
_DISPLAY_GROUP_SOURCE = None

def _display_group_names():
    """scene.display_group_names for the current export."""
    return list(_DISPLAY_GROUP_NAMES)

def _default_display_group(b):
    """Default rule: 0 (Points) for spheres, 1 (Others) for every other shape."""
    return 0 if _shape_name(b) == "sphere" else 1

def _display_group(b):
    """base_body.display_group of body b: from the dict {body_id: index} or the
    callable set by export_vtkhdf; 0 (the first group) otherwise."""
    src = _DISPLAY_GROUP_SOURCE
    if src is None:
        return 0
    if callable(src):
        return src(b)
    return src.get(b.id, 0)

def _collect(items, fields):
    """Evaluate every getter of fields on every item; a failing getter gives None."""
    cols = {}
    for name, _h, _mandatory, get in fields:
        vals = []
        for it in items:
            try: vals.append(get(it))
            except Exception: vals.append(None)
        cols[name] = vals
    return cols


def _export_scene(f):
    """Write /ONDEM/Scene — generated from scene schema."""
    grp = f.require_group("ONDEM/Scene")

    #  units: List[str] 
    hdf5_write_field(grp, "units", "string_list", ['second', 'meter', 'kilogram'], scalar_as_dataset=False)

    #  timestep: float [T]
    hdf5_write_field(grp, "timestep", "scalar_float", O.dt, scalar_as_dataset=False)

    #  time: float [T]
    hdf5_write_field(grp, "time", "scalar_float", O.time + (float(O.tags['ondem_time_offset']) if 'ondem_time_offset' in O.tags.keys() else 0.0), scalar_as_dataset=False)

    # [optional] iteration: int [$-$]
    hdf5_write_field(grp, "iteration", "scalar_int", O.iter + (int(O.tags['ondem_iteration_offset']) if 'ondem_iteration_offset' in O.tags.keys() else 0), scalar_as_dataset=False)

    #  gravity: Vector3 [L/T²]
    hdf5_write_field(grp, "gravity", "vector3", _get_gravity(), scalar_as_dataset=False)

    # [optional] display_group_names: List[str] [$-$]
    hdf5_write_field(grp, "display_group_names", "string_list", _display_group_names(), scalar_as_dataset=False)

    # [mandatory] shape_names: List[str] [$-$]
    hdf5_write_field(grp, "shape_names", "string_list", _shape_names(), scalar_as_dataset=False)


def _export_materials(f):
    """Write /ONDEM/Materials — generated from materials schema."""
    mat_grp = f.require_group("ONDEM/Materials")
    seen_ids = set()
    for b in O.bodies:
        if b is None or b.material is None: continue   # clump bodies have no material
        mat = b.material
        if mat.id in seen_ids: continue
        seen_ids.add(mat.id)
        g = mat_grp.create_group(str(mat.id))
        g.attrs["schema_classes"] = 'linear_elastic_frictional_3D'

        # Extra YADE-specific attributes (not in schema but useful)
        try: g.create_dataset("label", data=str(mat.label if mat.label else '').encode("utf-8"))
        except: pass
        try: g.create_dataset("material_type", data=str(type(mat).__name__).encode("utf-8"))
        except: pass
        try: g.create_dataset("yade_poisson", data=np.float64(mat.poisson))
        except: pass

        # --- linear_elastic_frictional_3D: Material with linear-elastic behaviour and sliding friction. ---
        # [mandatory] id: int [$-$]
        try:
            hdf5_write_field(g, "id", "scalar_int", mat.id, scalar_as_dataset=True)
        except Exception as _e:
            print(f"[export_vtkhdf] Warning: material {mat.id}: mandatory field id not written ({_e})")

        # [mandatory] density: float [$ML^{-3}$]
        try:
            hdf5_write_field(g, "density", "scalar_float", mat.density, scalar_as_dataset=True)
        except Exception as _e:
            print(f"[export_vtkhdf] Warning: material {mat.id}: mandatory field density not written ({_e})")

        # [mandatory] normal_stiffness: float [$FL^{-1}$]
        try:
            hdf5_write_field(g, "normal_stiffness", "scalar_float", mat.young, scalar_as_dataset=True)
        except Exception as _e:
            print(f"[export_vtkhdf] Warning: material {mat.id}: mandatory field normal_stiffness not written ({_e})")

        # [mandatory] shear_stiffness: float [$FL^{-1}$]
        try:
            hdf5_write_field(g, "shear_stiffness", "scalar_float", mat.young * mat.poisson, scalar_as_dataset=True)
        except Exception as _e:
            print(f"[export_vtkhdf] Warning: material {mat.id}: mandatory field shear_stiffness not written ({_e})")

        # [mandatory] shear_friction: float [$-$]
        try:
            hdf5_write_field(g, "shear_friction", "scalar_float", float(np.tan(mat.frictionAngle)), scalar_as_dataset=True)
        except Exception as _e:
            print(f"[export_vtkhdf] Warning: material {mat.id}: mandatory field shear_friction not written ({_e})")

        # [mandatory] shear_damping: float [$MT^{-1}$]
        try:
            hdf5_write_field(g, "shear_damping", "scalar_float", 0.0, scalar_as_dataset=True)
        except Exception as _e:
            print(f"[export_vtkhdf] Warning: material {mat.id}: mandatory field shear_damping not written ({_e})")


# Per-body fields: (name, hdf5 type, always written, getter).
# Generated from the schema; getters are the mapping expressions. A field that is
# not always written is written when at least one body has a value.
_BODY_FIELDS = [
    # [mandatory] base_body.material_id: int [$-$]
    ("material_id", "scalar_int", True, lambda b: b.material.id),
    # [mandatory] base_body.clump_id: int [$-$]
    ("clump_id", "scalar_int", True, lambda b: -1 if b.isClump else b.clumpId),
    # [mandatory] base_body.body_id: int [$-$]
    ("body_id", "scalar_int", True, lambda b: b.id),
    # SKIPPED base_body.body_state: nested type type(base_state)
    # SKIPPED base_body.body_shape: nested type type(base_shape)
    # [mandatory] base_body.shape_type: int [$-$]
    ("shape_type", "scalar_int", True, lambda b: _shape_type_index(b)),
    # [optional] base_body.clump_relative_position: Vector3 [$L$]
    ("clump_relative_position", "vector3", False, lambda b: O.bodies[b.clumpId].shape.members[b.id][0] if b.isClumpMember else None),
    # [optional] base_body.clump_relative_orientation: Quaternion [$-$]
    ("clump_relative_orientation", "quaternion", False, lambda b: (lambda q: [q[3], q[0], q[1], q[2]])(O.bodies[b.clumpId].shape.members[b.id][1]) if b.isClumpMember else None),
    # [mandatory] base_state.position: Vector3 [$L$]
    ("position", "vector3", True, lambda b: b.state.pos),
    # [mandatory] base_state.velocity: Vector3 [$L T^{-1}$]
    ("velocity", "vector3", True, lambda b: b.state.vel),
    # [mandatory] base_state.orientation: Quaternion [$-$]
    ("orientation", "quaternion", True, lambda b: [b.state.ori[3], b.state.ori[0], b.state.ori[1], b.state.ori[2]]),
    # [mandatory] base_state.angular_velocity: Vector3 [$T^{-1}$]
    ("angular_velocity", "vector3", True, lambda b: b.state.angVel),
    # [mandatory] base_state.mass: float [$M$]
    ("mass", "scalar_float", True, lambda b: b.state.mass),
    # [mandatory] base_state.inertia: Matrix3 [$M L^{2}$]
    ("inertia", "matrix3", True, lambda b: _diag3(b.state.inertia)),
    # [mandatory] base_state.volume: float [$L^{3}$]
    ("volume", "scalar_float", True, lambda b: _sphere_volume(b)),
    # [optional] base_state.blocked_dofs: int [$-$]
    ("blocked_dofs", "scalar_int", False, lambda b: sum(1 << 'xyzXYZ'.index(c) for c in b.state.blockedDOFs)),
    # [optional] thermal.temperature: float [$\Theta$]
    ("temperature", "scalar_float", False, lambda b: b.state.T),
    # [optional] liquid_film.liquid_film_volume: float [L^3]
    ("liquid_film_volume", "scalar_float", False, lambda b: b.state.liquidFilmVolume),
    # shape fields: NaN / -1 for bodies of other shapes
    # [mandatory] sphere.radius: float
    ("radius", "scalar_float", False, lambda b: b.shape.radius),
    # [mandatory] box.dimensions: Vector3
    ("dimensions", "vector3", False, lambda b: [b.shape.extents[0]*2, b.shape.extents[1]*2, b.shape.extents[2]*2]),
    # SKIPPED polyhedron.vertices: type list, variable length per body (see the shapes proposal)
    # wall: shape not in the schema yet (non-normative)
    ("wall_axis", "scalar_int", False, lambda b: b.shape.axis if type(b.shape).__name__ == 'Wall' else None),
    ("wall_sense", "scalar_int", False, lambda b: b.shape.sense if type(b.shape).__name__ == 'Wall' else None),
    # facet: shape not in the schema yet (non-normative)
    ("facet_vertices", "matrix3", False, lambda b: [[v[0],v[1],v[2]] for v in b.shape.vertices] if type(b.shape).__name__ == 'Facet' else None),
    ("facet_normal", "vector3", False, lambda b: b.shape.normal if type(b.shape).__name__ == 'Facet' else None),
    # not in the schema (provisional, not decided; mapping _extra_body_fields)
    ("group_mask", "scalar_int", True, lambda b: b.groupMask),
    ("is_damped", "scalar_bool", True, lambda b: b.state.isDamped),
    ("angular_momentum", "vector3", True, lambda b: b.state.angMom),
    ("density_scaling", "scalar_float", True, lambda b: b.state.densityScaling),
]

# code shape type -> schema shape name, and scene.shape_names (fixed list from the
# mapping; readers map shapes by name through the list, never by a fixed index)
_SHAPE_GROUPS = {'Sphere': 'sphere', 'Box': 'box', 'Polyhedra': 'polyhedron', 'Wall': 'wall', 'Facet': 'facet', 'Clump': 'clump'}
_SHAPE_NAMES = ['sphere', 'box', 'polyhedron', 'clump', 'wall', 'facet', 'other']

def _shape_names():
    """scene.shape_names."""
    return list(_SHAPE_NAMES)

def _shape_name(b):
    """Schema shape name of body b; "other" for shapes not supported yet."""
    try: return _SHAPE_GROUPS.get(type(b.shape).__name__, "other")
    except Exception: return "other"

def _shape_type_index(b):
    """base_body.shape_type: index of the shape name in scene.shape_names."""
    return _SHAPE_NAMES.index(_shape_name(b))

def _code_shape_type(b):
    try: return str(type(b.shape).__name__)
    except Exception: return "?"

def _export_bodies(f):
    """Write the bodies: one PolyData block per display group in /VTKHDF, every
    per-body field as PointData; Points = positions (float64)."""
    bodies = [b for b in O.bodies if b is not None]
    names = _display_group_names()
    cols = _collect(bodies, _BODY_FIELDS)
    body_ids = cols["body_id"]
    if None in body_ids or len(set(body_ids)) != len(body_ids):
        raise ValueError("[export_vtkhdf] body ids must be unique and defined")
    groups = [_display_group(b) for b in bodies]
    validate_display_groups(names, dict(zip(body_ids, groups)))
    other = sorted({_code_shape_type(b) for b in bodies if _shape_name(b) == 'other'})
    if other:
        print(f"[export_vtkhdf] Warning: shapes {other} are not supported by the format yet; "
              f"they are written with shape 'other' and cannot be restored")

    # the same arrays in every block: a field is written when it is always written
    # or when at least one body has a value; NaN / -1 elsewhere
    types = {name: h for name, h, _m, _g in _BODY_FIELDS}
    written = [name for name, h, always, _g in _BODY_FIELDS if name not in ("position", "body_id")
               and (always or any(v is not None for v in cols[name]))]

    vtkhdf_init_multiblock(f)
    for gi, name in enumerate(names):
        idx = [k for k, g in enumerate(groups) if g == gi]
        sel = lambda col: [col[k] for k in idx]
        vtkhdf_write_polydata_block(
            f, name, sel(body_ids),
            points=point_array(sel(cols["position"]), 3),
            point_data={n: column_array(sel(cols[n]), types[n]) for n in written},
            point_data_attrs={n: {"order": QUATERNION_ORDER} for n in written if types[n] == "quaternion"},
        )

    return len(bodies)


# Per-interaction fields: (name, hdf5 type, mandatory, getter).
_INTERACTION_FIELDS = [
    # UNMAPPED base_interaction.model
    # [mandatory] base_interaction.id1: int
    ("id1", "scalar_int", True, lambda i: i.id1),
    # [mandatory] base_interaction.id2: int
    ("id2", "scalar_int", True, lambda i: i.id2),
    # [optional] base_interaction.virtual: bool
    ("virtual", "scalar_bool", False, lambda i: not i.isReal),
    # UNMAPPED base_interaction.creation_time
    # [mandatory] normal.normal: Vector3 [$-$]
    ("normal", "vector3", True, lambda i: i.geom.normal),
    # [mandatory] normal.normal_force: float [$F$]
    ("normal_force", "scalar_float", True, lambda i: 0.0 - i.phys.normalForce.dot(i.geom.normal)),
    #  shear.shear_force: Vector3 [$F$]
    ("shear_force", "vector3", False, lambda i: i.phys.shearForce),
    # [mandatory] shear_linear.ks: float [$F/L$]
    ("ks", "scalar_float", True, lambda i: i.phys.ks),
    # [mandatory] normal_linear.kn: float [$F/L$]
    ("kn", "scalar_float", True, lambda i: i.phys.kn),
    # [mandatory] normal_hertz.hertz_young: float [$F/L²$]
    ("hertz_young", "scalar_float", True, lambda i: i.phys.young if hasattr(i.phys,'young') else float('nan')),
    # [mandatory] normal_hertz.hertz_poisson: float [$-$]
    ("hertz_poisson", "scalar_float", True, lambda i: i.phys.poisson if hasattr(i.phys,'poisson') else float('nan')),
    # [mandatory] linear_frictional_3D.friction_coefficient: float [$-$]
    ("friction_coefficient", "scalar_float", True, lambda i: i.phys.tangensOfFrictionAngle),
    # not in the schema (mapping _interaction_geometry)
    ("contact_point", "vector3", False, lambda i: i.geom.contactPoint),
    ("overlap", "scalar_float", False, lambda i: i.geom.penetrationDepth),
    ("reference_radius_1", "scalar_float", False, lambda i: i.geom.refR1),
    ("reference_radius_2", "scalar_float", False, lambda i: i.geom.refR2),
    # not in the schema (mapping _extra_interaction_attributes)
    ("geom_type", "string", False, lambda i: type(i.geom).__name__),
    ("phys_type", "string", False, lambda i: type(i.phys).__name__),
    ("normal_stiffness", "scalar_float", False, lambda i: i.phys.kn if hasattr(i.phys,'kn') else float('nan')),
    ("shear_stiffness", "scalar_float", False, lambda i: i.phys.ks if hasattr(i.phys,'ks') else float('nan')),
    ("frictional_dissipation", "scalar_float", False, lambda i: i.phys.frictDissip),
]

def _interaction_type(i):
    try: return snake_case(str(type(i.phys).__name__))
    except Exception: return "unknown"

def _export_interactions(f):
    """Write /ONDEM/Interactions/<type>/: one group per interaction type (snake_case)."""
    ig_root = f.require_group("ONDEM/Interactions")
    intrs = [i for i in O.interactions if i.isReal]
    by_type = {}
    for i in intrs:
        by_type.setdefault(_interaction_type(i), []).append(i)

    for itype in sorted(by_type):
        members = by_type[itype]
        ig = ig_root.create_group(itype)
        ig.attrs["count"] = len(members)
        cols = _collect(members, _INTERACTION_FIELDS)
        for name, h, mandatory, _get in _INTERACTION_FIELDS:
            vals = cols[name]
            if not mandatory and all(v is None for v in vals):
                continue
            hdf5_write_column(ig, name, vals, h)

    return len(intrs)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def export_vtkhdf(filename, display_group_names=None, display_group=None):
    """Export the current simulation state to an ON-DEM VTKHDF file (one timestep).

    Generated from schema: ../..
    Mapping file:          yade_mapping.json

    Parameters
    ----------
    filename : str
        Output file path (should end in .vtkhdf or .hdf).
    display_group_names : list of str, optional
        scene.display_group_names: one VTKHDF block per name, in this order.
    display_group : dict or callable, optional
        base_body.display_group of each body, an index into display_group_names:
        a dict {body_id: index} (bodies not in the dict get 0) or a callable
        body -> index. Requires display_group_names.

    Neither given: the default groups ['Points', 'Others'], spheres in Points and
    every other shape in Others. Names given without display_group: every body
    in the first group. Every group gets a block, also when it is empty.

    Raises ValueError (and writes no file) if display_group is given without
    display_group_names, if a name or an index is invalid, or if the scene
    cannot be written completely (mapping "_refuse_if", e.g. a periodic cell).
    """
    if O.periodic:
        raise ValueError('[export_vtkhdf] periodic scenes (O.periodic) are not supported yet: the periodic cell would not be written')
    global _DISPLAY_GROUP_NAMES, _DISPLAY_GROUP_SOURCE
    if display_group is not None and display_group_names is None:
        raise ValueError("[export_vtkhdf] display_group was given without display_group_names: "
                         "give the names of the groups it indexes (the defaults 'Points' / 'Others' "
                         "only go with the default rule)")
    if display_group_names is None:
        _DISPLAY_GROUP_NAMES = list(_DEFAULT_DISPLAY_GROUP_NAMES)
        _DISPLAY_GROUP_SOURCE = _default_display_group
    else:
        _DISPLAY_GROUP_NAMES = list(display_group_names)
        _DISPLAY_GROUP_SOURCE = display_group

    try:
        with h5py.File(filename, "w") as f:

            # 1. Bodies: /VTKHDF blocks (one per display group) + /ONDEM/Bodies
            n_bodies = _export_bodies(f)

            # 2. Scene metadata (includes display_group_names)
            _export_scene(f)

            # 3. Materials
            _export_materials(f)

            # 4. Interactions
            n_intrs = _export_interactions(f)

            # Top-level metadata
            f.attrs["file_format"]         = "ON-DEM VTKHDF"
            f.attrs["file_format_version"] = "0.2-draft"
            f.attrs["schema_dir"]          = "../.."
            f.attrs["mapping_file"]        = "yade_mapping.json"
    except Exception:
        # do not leave a half-written file behind
        if os.path.exists(filename):
            os.remove(filename)
        raise

    print(f"[export_vtkhdf] Exported {n_bodies} bodies in {len(_DISPLAY_GROUP_NAMES)} display group(s), "
          f"{n_intrs} interactions at t={O.time + (float(O.tags['ondem_time_offset']) if 'ondem_time_offset' in O.tags.keys() else 0.0):.6g} to '{filename}'")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "output.vtkhdf"
    export_vtkhdf(out)
