"""
export_yade_vtkhdf.py
ON-DEM WG3 - YADE to VTKHDF exporter

AUTO-GENERATED by codegen_yade.py on 2026-04-09
  Schema dir : /home/3S-LAB/bchareyre/Documents/ON-DEM/wp3-data/model-data
  Mapping    : yade_mapping.json

DO NOT EDIT MANUALLY - re-run the generator to update.

Usage (inside YADE or from yadedaily -x):
    from export_yade_vtkhdf import export_vtkhdf
    export_vtkhdf("output.vtkhdf")

Periodic engine usage:
    O.engines += [PyRunner(
        command='export_vtkhdf("sim_%04d.vtkhdf" % O.iter)',
        iterPeriod=1000)]
"""

import numpy as np
import h5py
import os
import sys

from hdf5_utils import hdf5_write_field, hdf5_write_scalar_array, hdf5_write_vector3_array, hdf5_write_quaternion_array, hdf5_write_matrix3_array, hdf5_write_string_array


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_gravity():
    """YADE gravity lives on NewtonIntegrator, not on O directly."""
    for eng in O.engines:
        if type(eng).__name__ == "NewtonIntegrator":
            g = eng.gravity
            return [g[0], g[1], g[2]]
    return [0.0, 0.0, 0.0]

def _sphere_volume(b):
    r = b.shape.radius
    return 4.0 / 3.0 * 3.141592653589793 * r**3

def _vec3(v):
    return np.array([v[0], v[1], v[2]], dtype=np.float64)

def _quat(q):
    """YADE: q[0]=w → store as [x,y,z,w]"""
    return np.array([q[1], q[2], q[3], q[0]], dtype=np.float64)

def _mat3_flat(iv):
    """YADE inertia is a Vector3 of principal moments → diagonal 3x3, row-major."""
    return np.array([iv[0],0,0, 0,iv[1],0, 0,0,iv[2]], dtype=np.float64)


def _export_scene(f):
    """Write /ONDEM/Scene — generated from scene schema."""
    grp = f.require_group("ONDEM/Scene")

    #  units: <_ast.Subscript object at 0x7fda0a405100> 
    hdf5_write_field(grp, "units", "unknown", ['second', 'meter', 'kilogram'], scalar_as_dataset=False)

    #  timestep: <_ast.Name object at 0x7fda0a4059d0> [T]
    hdf5_write_field(grp, "timestep", "unknown", O.dt, scalar_as_dataset=False)

    #  time: <_ast.Name object at 0x7fda0a405cd0> [T]
    hdf5_write_field(grp, "time", "unknown", O.time, scalar_as_dataset=False)

    #  gravity: <_ast.Name object at 0x7fda0a405e80> [L/T²]
    hdf5_write_field(grp, "gravity", "unknown", _get_gravity(), scalar_as_dataset=False)


def _export_materials(f):
    """Write /ONDEM/Materials — generated from materials schema."""
    mat_grp = f.require_group("ONDEM/Materials")
    seen_ids = set()
    for b in O.bodies:
        if b is None: continue
        mat = b.material
        if mat.id in seen_ids: continue
        seen_ids.add(mat.id)
        g = mat_grp.create_group(str(mat.id))

        # Extra YADE-specific attributes (not in schema but useful)
        try: g.create_dataset("friction_angle_rad", data=np.float64(float(mat.frictionAngle) if hasattr(mat,'frictionAngle') else 0.0))
        except: pass
        try: g.create_dataset("label", data=np.bytes_(str(mat.label if mat.label else '')))
        except: pass
        try: g.create_dataset("material_type", data=np.bytes_(str(type(mat).__name__)))
        except: pass
        try: g.create_dataset("yade_material_type", data=np.bytes_(str(type(mat).__name__)))
        except: pass

        # --- material_general: These are shared material variables for all materials ---
        # [mandatory] density: <_ast.Name object at 0x7fda0a409160> [$M L^{-3}$]
        try:
            hdf5_write_field(g, "density", "unknown", mat.density, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] friction_coefficient: <_ast.Name object at 0x7fda0a409220> [$-$]
        try:
            hdf5_write_field(g, "friction_coefficient", "unknown", float(np.tan(mat.frictionAngle)) if hasattr(mat,'frictionAngle') else 0.0, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] id: <_ast.Name object at 0x7fda0a409100> [$-$]
        try:
            hdf5_write_field(g, "id", "unknown", mat.id, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # --- material_spring_constants: This material describes linear-elastic behaviour with spring constants ---
        # [mandatory] normal_stiffness: <_ast.Name object at 0x7fda0a409cd0> [$F L^{-1}$]
        try:
            hdf5_write_field(g, "normal_stiffness", "unknown", mat.kn, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] shear_stiffness: <_ast.Name object at 0x7fda0a409d60> [$F L^{-1}$]
        try:
            hdf5_write_field(g, "shear_stiffness", "unknown", mat.ks, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # --- material_elastic_constants: This material describes linear-elastic behaviour with elasticity parameters ---
        # [mandatory] young: <_ast.Name object at 0x7fda0a409df0> [$F L^{-2}$]
        try:
            hdf5_write_field(g, "young", "unknown", mat.young, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] poisson: <_ast.Name object at 0x7fda0a482ee0> [$-$]
        try:
            hdf5_write_field(g, "poisson", "unknown", mat.poisson, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # --- material_visco_elastic_constants_COR: This material describes visco-elastic behaviour with constant coefficient of restitution ---
        # [mandatory] damping_coefficient_normal: <_ast.Name object at 0x7fda0a405d00> [$M T^{-1}$]
        try:
            hdf5_write_field(g, "damping_coefficient_normal", "unknown", mat.cn, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # [mandatory] damping_coefficient_shear: <_ast.Name object at 0x7fda0a405e20> [$M T^{-1}$]
        try:
            hdf5_write_field(g, "damping_coefficient_shear", "unknown", mat.cs, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type

        # --- material_visco_elastic_variable_COR: This material describes visco-elastic behaviour with variable coefficient of restitution ---
        # [mandatory] dissipative_constant: <_ast.Name object at 0x7fda0a405d90> [$-$]
        try:
            hdf5_write_field(g, "dissipative_constant", "unknown", mat.alpha, scalar_as_dataset=True)
        except Exception as _e:
            pass  # field not available for this material type


def _export_bodies(f):
    """Write bodies separated by shape type to /ONDEM/Bodies/ — generated from schema."""

    bodies_grp = f.require_group("ONDEM/Bodies")

    shape_types = ['Sphere', 'Box', 'Polyhedron', 'Wall', 'Facet']

    for shape_type in shape_types:
        bodies = [b for b in O.bodies if b is not None and type(b.shape).__name__ == shape_type]
        if not bodies: continue

        bg = bodies_grp.require_group(shape_type)
        bg.attrs['count'] = len(bodies)

        # --- Collect body data ---
        _material_id_list = []
        _clump_id_list = []
        _body_id_list = []
        _position_list = []
        _velocity_list = []
        _orientation_list = []
        _angular_velocity_list = []
        _mass_list = []
        _inertia_list = []
        _volume_list = []
        _radius_list = []
        _dimensions_list = []
        _vertices_list = []

        for b in bodies:

            try: _material_id_list.append(b.material.id)
            except: _material_id_list.append(None)
            try: _clump_id_list.append(b.clumpId)
            except: _clump_id_list.append(None)
            try: _body_id_list.append(b.id)
            except: _body_id_list.append(None)
            try: _position_list.append(b.state.pos)
            except: _position_list.append(None)
            try: _velocity_list.append(b.state.vel)
            except: _velocity_list.append(None)
            try: _orientation_list.append(b.state.ori)
            except: _orientation_list.append(None)
            try: _angular_velocity_list.append(b.state.angVel)
            except: _angular_velocity_list.append(None)
            try: _mass_list.append(b.state.mass)
            except: _mass_list.append(None)
            try: _inertia_list.append(b.state.inertia)
            except: _inertia_list.append(None)
            try: _volume_list.append(_sphere_volume(b))
            except: _volume_list.append(None)
            try: _radius_list.append(b.shape.radius)
            except: _radius_list.append(None)
            try: _dimensions_list.append([b.shape.extents[0]*2, b.shape.extents[1]*2, b.shape.extents[2]*2])
            except: _dimensions_list.append(None)
            try: _vertices_list.append([[v[0],v[1],v[2]] for v in b.shape.vertices])
            except: _vertices_list.append(None)

        # --- Write datasets ---
        # [mandatory] material_id: <_ast.Name object at 0x7fda0a405d60> [$-$]
        # SKIPPED dataset for material_id (type=unknown)

        # [mandatory] clump_id: <_ast.Name object at 0x7fda0a405eb0> [$-$]
        # SKIPPED dataset for clump_id (type=unknown)

        # [mandatory] body_id: <_ast.Name object at 0x7fda0a409040> [$-$]
        # SKIPPED dataset for body_id (type=unknown)

        # [mandatory] position: <_ast.Name object at 0x7fda0a41b280> [$L$]
        # SKIPPED dataset for position (type=unknown)

        # [mandatory] velocity: <_ast.Name object at 0x7fda0a41b460> [$L T^{-1}$]
        # SKIPPED dataset for velocity (type=unknown)

        # [mandatory] orientation: <_ast.Name object at 0x7fda0a41b670> [$-$]
        # SKIPPED dataset for orientation (type=unknown)

        # [mandatory] angular_velocity: <_ast.Name object at 0x7fda0a41b8b0> [$T^{-1}$]
        # SKIPPED dataset for angular_velocity (type=unknown)

        # [mandatory] mass: <_ast.Name object at 0x7fda0a41bac0> [$M$]
        # SKIPPED dataset for mass (type=unknown)

        # [mandatory] inertia: <_ast.Name object at 0x7fda0a41bc10> [$M L^{2}$]
        # SKIPPED dataset for inertia (type=unknown)

        # [mandatory] volume: <_ast.Name object at 0x7fda0a41bdc0> [$L^{3}$]
        # SKIPPED dataset for volume (type=unknown)

        # [mandatory] radius: <_ast.Name object at 0x7fda0a4055e0> 
        # SKIPPED dataset for radius (type=unknown)

        # [mandatory] dimensions: <_ast.Name object at 0x7fda0a405820> 
        # SKIPPED dataset for dimensions (type=unknown)

        # [mandatory] vertices: <_ast.Name object at 0x7fda0a405b50> 
        # SKIPPED dataset for vertices (type=unknown)


    # --- Unified VTK PolyData for all bodies ---
    bodies = [b for b in O.bodies if b is not None]
    N = len(bodies)
    if N == 0:
        print("[export_vtkhdf] Warning: no bodies found")
        return 0

    vtk = f.require_group("VTKHDF")
    vtk.attrs.create("Type",    data=np.bytes_("PolyData"))
    vtk.attrs.create("Version", data=np.array([2, 0], dtype=np.int64))

    # Points = body centres
    positions = [b.state.pos for b in bodies]
    hdf5_write_vector3_array(vtk, "Points", positions)
    vtk.create_dataset("NumberOfPoints", data=np.array([N], dtype=np.int64))

    # Empty cell structures (required by VTK HDF spec for PolyData)
    for _sec in ["Verts","Lines","Polygons","Strips"]:
        _sg = vtk.require_group(_sec)
        _sg.create_dataset("NumberOfCells",           data=np.array([0], dtype=np.int64))
        _sg.create_dataset("NumberOfConnectivityIds", data=np.array([0], dtype=np.int64))
        _sg.create_dataset("Offsets",                 data=np.array([0], dtype=np.int64))
        _sg.create_dataset("Connectivity",            data=np.array([], dtype=np.int64))

    pd = vtk.require_group("PointData")

    # Shape types
    shape_types_list = [type(b.shape).__name__ for b in bodies]
    hdf5_write_string_array(pd, "shape_type", shape_types_list)

    return N


def _export_interactions(f):
    """Write /ONDEM/Interactions — generated from interaction schema, separated by type."""
    ig_root = f.require_group("ONDEM/Interactions")

    intr_types = ['Normal', 'Shear', 'NormalLinear', 'ShearLinear', 'NormalHertz', 'Intr', 'Intr3D']

    for phys_type in intr_types:
        intrs = [i for i in O.interactions if i.isReal and type(i.phys).__name__ == phys_type]
        if not intrs: continue

        ig = ig_root.require_group(phys_type)
        ig.attrs['count'] = len(intrs)

        # --- Accumulate per-interaction data ---
        _id1_list = []
        _id2_list = []
        _virtual_list = []
        _lifespan_list = []
        _normal_list = []
        _normal_force_list = []
        _shear_force_list = []
        _ks_list = []
        _hertz_young_list = []
        _hertz_poisson_list = []
        _contact_point_list = []
        _overlap_list = []
        _reference_radius_1_list = []
        _reference_radius_2_list = []
        _geom_type_list = []
        _phys_type_list = []
        _normal_stiffness_list = []
        _shear_stiffness_list = []
        _friction_coefficient_interaction_list = []
        _normal_damping_ratio_list = []
        _shear_damping_ratio_list = []
        _isSliding_list = []
        _shear_force_elastic_list = []
        _shear_force_viscous_list = []
        _normal_force_viscous_list = []

        for i in intrs:

            try: _id1_list.append(i.id1)
            except: _id1_list.append(None)
            try: _id2_list.append(i.id2)
            except: _id2_list.append(None)
            try: _virtual_list.append(not i.isReal)
            except: _virtual_list.append(None)
            try: _lifespan_list.append(i.phys.lifespan if hasattr(i.phys,'lifespan') else 0.0)
            except: _lifespan_list.append(None)
            try: _normal_list.append(i.geom.normal)
            except: _normal_list.append(None)
            try: _normal_force_list.append(i.phys.normalForce.norm())
            except: _normal_force_list.append(None)
            try: _shear_force_list.append(i.phys.shearForce)
            except: _shear_force_list.append(None)
            try: _ks_list.append(i.phys.ks)
            except: _ks_list.append(None)
            try: _hertz_young_list.append(i.phys.kno)
            except: _hertz_young_list.append(None)
            try: _hertz_poisson_list.append(i.phys.kso)
            except: _hertz_poisson_list.append(None)
            try: _contact_point_list.append(i.geom.contactPoint)
            except: _contact_point_list.append(None)
            try: _overlap_list.append(i.geom.penetrationDepth)
            except: _overlap_list.append(None)
            try: _reference_radius_1_list.append(i.geom.refR1)
            except: _reference_radius_1_list.append(None)
            try: _reference_radius_2_list.append(i.geom.refR2)
            except: _reference_radius_2_list.append(None)
            try: _geom_type_list.append(type(i.geom).__name__)
            except: _geom_type_list.append(None)
            try: _phys_type_list.append(type(i.phys).__name__)
            except: _phys_type_list.append(None)
            try: _normal_stiffness_list.append(i.phys.kn  if hasattr(i.phys,'kn')  else 0.0)
            except: _normal_stiffness_list.append(None)
            try: _shear_stiffness_list.append(i.phys.ks  if hasattr(i.phys,'ks')  else 0.0)
            except: _shear_stiffness_list.append(None)
            try: _friction_coefficient_interaction_list.append(i.phys.tangensOfFrictionAngle if hasattr(i.phys,'tangensOfFrictionAngle') else 0.0)
            except: _friction_coefficient_interaction_list.append(None)
            try: _normal_damping_ratio_list.append(i.phys.betan if hasattr(i.phys,'betan') else float('nan'))
            except: _normal_damping_ratio_list.append(None)
            try: _shear_damping_ratio_list.append(i.phys.betas if hasattr(i.phys,'betas') else float('nan'))
            except: _shear_damping_ratio_list.append(None)
            try: _isSliding_list.append(int(i.phys.isSliding) if hasattr(i.phys,'isSliding') else 0)
            except: _isSliding_list.append(None)
            try: _shear_force_elastic_list.append(i.phys.shearElastic if hasattr(i.phys,'shearElastic') else None)
            except: _shear_force_elastic_list.append(None)
            try: _shear_force_viscous_list.append(i.phys.shearViscous  if hasattr(i.phys,'shearViscous')  else None)
            except: _shear_force_viscous_list.append(None)
            try: _normal_force_viscous_list.append(i.phys.normalViscous.norm() if hasattr(i.phys,'normalViscous') else float('nan'))
            except: _normal_force_viscous_list.append(None)

        # --- Write datasets ---
        # id1: <_ast.Name object at 0x7fda0a4094f0> 
        # SKIPPED id1 (type=unknown)

        # id2: <_ast.Name object at 0x7fda0a409190> 
        # SKIPPED id2 (type=unknown)

        # virtual: <_ast.Name object at 0x7fda0a4092e0> 
        # SKIPPED virtual (type=unknown)

        # lifespan: <_ast.Name object at 0x7fda0a4093a0> 
        # SKIPPED lifespan (type=unknown)

        # normal: <_ast.Name object at 0x7fda0a409460> [$-$]
        # SKIPPED normal (type=unknown)

        # normal_force: <_ast.Name object at 0x7fda0a409e50> [$F$]
        # SKIPPED normal_force (type=unknown)

        # shear_force: <_ast.Name object at 0x7fda0a405c70> [$F$]
        # SKIPPED shear_force (type=unknown)

        # ks: <_ast.Name object at 0x7fda0a405070> [$F/L$]
        # SKIPPED ks (type=unknown)

        # hertz_young: <_ast.Name object at 0x7fda0a405580> [$F/L²$]
        # SKIPPED hertz_young (type=unknown)

        # hertz_poisson: <_ast.Name object at 0x7fda0a4054f0> [$-$]
        # SKIPPED hertz_poisson (type=unknown)

        hdf5_write_vector3_array(ig, "contact_point", _contact_point_list)

        hdf5_write_scalar_array(ig, "overlap", _overlap_list, np.float64)

        hdf5_write_scalar_array(ig, "reference_radius_1", _reference_radius_1_list, np.float64)

        hdf5_write_scalar_array(ig, "reference_radius_2", _reference_radius_2_list, np.float64)

        hdf5_write_string_array(ig, "geom_type", _geom_type_list)

        hdf5_write_string_array(ig, "phys_type", _phys_type_list)

        hdf5_write_scalar_array(ig, "normal_stiffness", _normal_stiffness_list, np.float64)

        hdf5_write_scalar_array(ig, "shear_stiffness", _shear_stiffness_list, np.float64)

        hdf5_write_scalar_array(ig, "friction_coefficient_interaction", _friction_coefficient_interaction_list, np.float64)

        hdf5_write_scalar_array(ig, "normal_damping_ratio", _normal_damping_ratio_list, np.float64)

        hdf5_write_scalar_array(ig, "shear_damping_ratio", _shear_damping_ratio_list, np.float64)

        hdf5_write_scalar_array(ig, "isSliding", _isSliding_list, np.int32)

        hdf5_write_vector3_array(ig, "shear_force_elastic", _shear_force_elastic_list)

        hdf5_write_vector3_array(ig, "shear_force_viscous", _shear_force_viscous_list)

        hdf5_write_scalar_array(ig, "normal_force_viscous", _normal_force_viscous_list, np.float64)


    return

def _export_nonsphere_bodies(f):
    """Write /ONDEM/Bodies — walls, facets, boxes."""
    grp = f.require_group("ONDEM/Bodies")
    walls, facets, boxes, others = [], [], [], []
    for b in O.bodies:
        if b is None: continue
        stype = type(b.shape).__name__
        if stype == 'Sphere': continue
        elif stype == 'Wall':      walls.append(b)
        elif stype == 'Facet':     facets.append(b)
        elif stype == 'Box':       boxes.append(b)
        else:                      others.append(b)

    # --- Walls ---
    if walls:
        wg = grp.require_group('Walls')
        wg.create_dataset('body_id',     data=np.array([b.id for b in walls],            dtype=np.int32))
        wg.create_dataset('material_id', data=np.array([b.material.id for b in walls],   dtype=np.int32))
        wg.create_dataset('axis',        data=np.array([b.shape.axis for b in walls], dtype=np.int32))
        wg.create_dataset('sense',       data=np.array([b.shape.sense for b in walls], dtype=np.int32))
        wg.create_dataset('position',    data=np.array([[b.state.pos[0],b.state.pos[1],b.state.pos[2]] for b in walls], dtype=np.float64))
        wg.attrs['shape_type'] = 'wall'
        wg.attrs['count'] = len(walls)

    # --- Facets ---
    if facets:
        fg = grp.require_group('Facets')
        fg.create_dataset('body_id',     data=np.array([b.id for b in facets], dtype=np.int32))
        fg.create_dataset('material_id', data=np.array([b.material.id for b in facets], dtype=np.int32))
        fg.create_dataset('vertices',    data=np.array([[[v[0],v[1],v[2]] for v in b.shape.vertices] for b in facets], dtype=np.float64))
        fg.create_dataset('normal',      data=np.array([[b.shape.normal[0],b.shape.normal[1],b.shape.normal[2]] for b in facets], dtype=np.float64))
        fg.create_dataset('position',    data=np.array([[b.state.pos[0],b.state.pos[1],b.state.pos[2]] for b in facets], dtype=np.float64))
        fg.attrs['shape_type'] = 'facet'
        fg.attrs['count'] = len(facets)

    # --- Boxes (ON-DEM schema: box.dimensions) ---
    if boxes:
        bg = grp.require_group('Boxes')
        bg.create_dataset('body_id',     data=np.array([b.id for b in boxes], dtype=np.int32))
        bg.create_dataset('material_id', data=np.array([b.material.id for b in boxes], dtype=np.int32))
        bg.create_dataset('dimensions',  data=np.array([[b.shape.extents[0]*2,b.shape.extents[1]*2,b.shape.extents[2]*2] for b in boxes], dtype=np.float64))
        bg.create_dataset('position',    data=np.array([[b.state.pos[0],b.state.pos[1],b.state.pos[2]] for b in boxes], dtype=np.float64))
        bg.create_dataset('orientation', data=np.array([[b.state.ori[1],b.state.ori[2],b.state.ori[3],b.state.ori[0]] for b in boxes], dtype=np.float64))
        bg.attrs['shape_type'] = 'box'
        bg.attrs['count'] = len(boxes)

    # --- Other shapes (best effort) ---
    if others:
        og = grp.require_group('Other')
        og.create_dataset('body_id', data=np.array([b.id for b in others], dtype=np.int32))
        _dt = h5py.special_dtype(vlen=str)
        _ds = og.create_dataset('shape_type', (len(others),), dtype=_dt)
        for _ii, b in enumerate(others): _ds[_ii] = type(b.shape).__name__
        og.attrs['note'] = 'shape type not fully supported by ON-DEM schema yet'


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def export_vtkhdf(filename):
    """Export the current YADE simulation state to an ON-DEM VTKHDF file.

    Generated from schema: /home/3S-LAB/bchareyre/Documents/ON-DEM/wp3-data/model-data
    Mapping file:          yade_mapping.json

    Parameters
    ----------
    filename : str
        Output file path (should end in .vtkhdf or .hdf).
    """
    with h5py.File(filename, "w") as f:

        # 1. VTK PolyData for all bodies (/VTKHDF/)
        n_bodies = _export_bodies(f)

        # 2. Scene metadata
        _export_scene(f)

        # 3. Materials
        _export_materials(f)

        # 4. Non-sphere bodies
        _export_nonsphere_bodies(f)

        # 5. Interactions
        _export_interactions(f)

        # Top-level metadata
        f.attrs["file_format"]         = "ON-DEM VTKHDF"
        f.attrs["file_format_version"] = "0.1-draft"
        f.attrs["source_code"]         = "YADE"
        f.attrs["schema_dir"]          = "/home/3S-LAB/bchareyre/Documents/ON-DEM/wp3-data/model-data"
        f.attrs["mapping_file"]        = "yade_mapping.json"

    n_intrs = sum(1 for i in O.interactions if i.isReal)
    print(f"[export_vtkhdf] Exported {n_bodies} bodies, {n_intrs} interactions "
          f"at t={O.time:.6g} to \'{filename}\'")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "output.vtkhdf"
    export_vtkhdf(out)
